### GET request for red alerts from IDF's home front command with minimal headers
# @no-cookie-jar
GET https://www.oref.org.il/WarningMessages/alert/alerts.json
Accept: application/json

### GET request for IDF's home front command districts per language code
# @no-cookie-jar
GET https://www.oref.org.il/Shared/Ajax/GetDistricts.aspx?lang={{languageCode}}
Accept: application/json
