package il.co;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

public enum LanguageUtil
{
	HE(new HashSet<>(Arrays.asList(
			"אזור תעשייה שחורת",
			"אילות",
			"אילת",
			"אבו-גוש",
			"אביעזר",
			"אבן ספיר",
			"אדרת",
			"אורה",
			"אזור תעשייה ברוש",
			"אזור תעשייה הר טוב - צרעה",
			"אשתאול",
			"בית זית",
			"בית מאיר",
			"בית נקופה",
			"בית שמש",
			"בקוע",
			"בר גיורא",
			"גבעות עדן",
			"גבעת יערים",
			"גבעת ישעיהו",
			"גיזו",
			"גפן",
			"הר אדר",
			"הראל",
			"זכריה",
			"זנוח",
			"טל שחר",
			"יד השמונה",
			"ישעי",
			"כסלון",
			"כפר אוריה",
			"כפר זוהרים",
			"לוזית",
			"לטרון",
			"מבוא ביתר",
			"מבשרת ציון",
			"מוצא עילית",
			"מחסיה",
			"מטע",
			"מסילת ציון",
			"מעלה החמישה",
			"נווה אילן",
			"נווה מיכאל - רוגלית",
			"נווה שלום",
			"נחושה",
			"נחם",
			"נחשון",
			"נטף",
			"נס הרים",
			"נתיב הל''ה",
			"עגור",
			"עין נקובא",
			"עין ראפה",
			"עמינדב",
			"צובה",
			"צור הדסה",
			"צלפון",
			"צפרירים",
			"צרעה",
			"קריית יערים",
			"קריית ענבים",
			"רטורנו - גבעת שמש",
			"רמת רזיאל",
			"שדות מיכה",
			"שואבה",
			"שורש",
			"שריגים - ליאון",
			"תירוש",
			"תעוז",
			"תרום",
			"ארגמן",
			"בקעות",
			"גיתית",
			"גלגל",
			"חמדת",
			"חמרה",
			"ייט''ב",
			"יפית",
			"מבואות יריחו",
			"מחולה",
			"מכורה",
			"מעלה אפרים",
			"משואה",
			"משכיות",
			"נעמה",
			"נערן",
			"נתיב הגדוד",
			"פצאל",
			"רועי",
			"רותם",
			"שדמות מחולה",
			"תומר",
			"אזור תעשייה צבאים",
			"בית אלפא וחפציבה",
			"בית השיטה",
			"בית יוסף",
			"בית שאן",
			"גשר",
			"חוות עדן",
			"חמדיה",
			"חפציבה ובית אלפא",
			"טירת צבי",
			"ירדנה",
			"כפר גמילה מלכישוע",
			"כפר רופין",
			"מולדת",
			"מירב",
			"מנחמיה",
			"מסילות",
			"מעוז חיים",
			"מעלה גלבוע",
			"נווה אור",
			"נווה איתן",
			"ניר דוד",
			"עין הנצי''ב",
			"רוויה",
			"רחוב",
			"רשפים",
			"שדה אליהו",
			"שדה נחום",
			"שדי תרומות",
			"שלוחות",
			"שלפים",
			"תל תאומים",
			"אבני איתן",
			"אודם",
			"אורטל",
			"אזור תעשייה בני יהודה",
			"אל רום",
			"אלוני הבשן",
			"אלי עד",
			"אפיק",
			"בוקעתא",
			"בני יהודה וגבעת יואב",
			"גבעת יואב ובני יהודה",
			"גשור",
			"חמת גדר",
			"חספין",
			"יונתן",
			"כפר חרוב",
			"מבוא חמה",
			"מג'דל שמס",
			"מיצר",
			"מסעדה",
			"מרום גולן",
			"נאות גולן",
			"נוב",
			"נווה אטי''ב",
			"נטור",
			"נמרוד",
			"עין זיוון",
			"עין קנייא",
			"קשת",
			"רמת מגשימים",
			"Kamanneh",
			"אבו סנאן",
			"אור הגנוז",
			"אזור תעשייה חצור הגלילית",
			"אזור תעשייה כרמיאל",
			"אזור תעשייה צ.ח.ר",
			"איילת השחר",
			"אליפלט",
			"אמירים",
			"אמנון",
			"אשרת",
			"בוסתן הגליל",
			"ביריה",
			"בית ג'אן",
			"בית העמק",
			"בענה",
			"בר יוחאי",
			"גדות",
			"ג'דידה מכר",
			"ג'וליס",
			"גילון צורית",
			"גיתה",
			"דיר אל-אסד",
			"הר-חלוץ",
			"חולתה",
			"חצור הגלילית",
			"חרשים",
			"טובא זנגריה",
			"טל-אל",
			"ינוח-ג'ת",
			"יסוד המעלה",
			"ירכא",
			"כורזים ורד הגליל",
			"כחל",
			"כיסרא",
			"כישור",
			"כליל",
			"כפר הנשיא",
			"כפר יסיף",
			"כפר מסריק",
			"כפר שמאי",
			"כרכום",
			"כרמיאל",
			"לבון",
			"לוחמי הגטאות",
			"לפידות",
			"מג'דל כרום",
			"מגדל תפן",
			"מזרעה",
			"מחניים",
			"מירון",
			"מנחת מחניים",
			"משמר הירדן",
			"נחף",
			"נס עמים",
			"נתיב השיירה",
			"סאג'ור",
			"סמיע",
			"ספסופה - כפר חושן",
			"עין אל אסד",
			"עין המפרץ",
			"עין כמונים",
			"עכו",
			"עכו - אזור תעשייה",
			"עמוקה",
			"עמיעד",
			"עמקה",
			"פלך",
			"פרוד",
			"צורית גילון",
			"צפת",
			"קדיתא",
			"קדרים",
			"ראמה",
			"ראש פינה",
			"רגבה",
			"שדה אליעזר",
			"שומרת",
			"שזור",
			"שייח' דנון",
			"שפר",
			"תובל",
			"אבטליון",
			"אוהלו ובית ירח",
			"אזור תעשייה בר-לב",
			"אזור תעשייה צמח",
			"אזור תעשייה קדמת גליל",
			"אזור תעשייה תרדיון",
			"אחיהוד",
			"אילניה",
			"אלומות",
			"אעבלין",
			"אפיקים",
			"אפק",
			"ארבל",
			"אשבל",
			"אשדות יעקב איחוד",
			"אשדות יעקב מאוחד",
			"אשחר",
			"בועיינה-נוג'ידאת",
			"ביר אלמכסור",
			"בית זרע",
			"בית קשת",
			"בית רימון",
			"גינוסר",
			"דגניה א",
			"דגניה ב",
			"דיר חנא",
			"דמיידה",
			"הודיות",
			"הזורעים",
			"המכללה האקדמית כנרת",
			"הר כמון - מזרח",
			"הר כמון - מערב",
			"הררית יחד",
			"חוסנייה",
			"חוקוק",
			"חזון",
			"טבריה",
			"טמרה",
			"טפחות",
			"יבנאל",
			"יובלים",
			"יודפת",
			"יסעור",
			"יעד",
			"כאבול",
			"כאוכב אבו אלהיג'א",
			"כדורי",
			"כינרת מושבה",
			"כינרת קבוצה",
			"כלנית",
			"כפר זיתים",
			"כפר חיטים",
			"כפר חנניה",
			"כפר כמא",
			"כפר מנדא",
			"לביא",
			"לבנים",
			"לוטם וחמדון",
			"מגדל",
			"מורן",
			"מורשת",
			"מנוף",
			"מסד",
			"מע'אר",
			"מעלה צביה",
			"מצפה",
			"מצפה אבי''ב",
			"מצפה נטופה",
			"מרכז אזורי משגב",
			"סכנין",
			"סלמה",
			"עילבון",
			"עינבר",
			"עצמון - שגב",
			"עראבה",
			"ערב אל-נעים",
			"פוריה כפר עבודה",
			"פוריה נווה עובד",
			"פוריה עילית",
			"קורנית",
			"ראס אל-עין",
			"רביד",
			"רקפת",
			"שדה אילן",
			"שדמות דבורה",
			"שורשים",
			"שכניה",
			"שעב",
			"שפרעם",
			"שרונה",
			"אור יהודה",
			"אזור",
			"בני ברק",
			"בת-ים",
			"גבעת שמואל",
			"גבעתיים",
			"גני תקווה",
			"חולון",
			"יהוד-מונוסון",
			"מקווה ישראל",
			"סביון",
			"קריית אונו",
			"רמת גן - מזרח",
			"רמת גן - מערב",
			"תל אביב - דרום העיר ויפו",
			"תל אביב - מזרח",
			"תל אביב - מרכז העיר",
			"תל אביב - עבר הירקון",
			"Al-Sayyid",
			"אבו קרינאת והפזורה",
			"אבו-תלול והפזורה",
			"אום בטין והפזורה",
			"אזור תעשייה דימונה",
			"אזור תעשייה רותם",
			"אשלים",
			"באר מילכה",
			"ביר הדאג'",
			"בית סוהר נפחא",
			"דימונה",
			"דריג'את, תל ערד ואל פורה",
			"ואדי אל נעם",
			"חורה",
			"טללים",
			"ירוחם",
			"כוחלה מכחול",
			"כמהין",
			"כסייפה והפזורה",
			"מדרשת בן גוריון",
			"מולדה, אל-סייד והפזורה",
			"מכחול וכוחלה",
			"מצפה רמון",
			"מרחב עם",
			"משאבי שדה",
			"מתחם צומת שוקת",
			"ניצנה",
			"עבדת",
			"עזוז",
			"ערד",
			"ערוער - ערערה בנגב",
			"קדש ברנע",
			"קצר-א-סיר והפזורה",
			"רביבים",
			"רתמים",
			"שאנטי במדבר",
			"שגב שלום והפזורה",
			"שדה בוקר",
			"תל שבע",
			"בית אלעזרי",
			"בית גמליאל",
			"בית חלקיה",
			"בן זכאי",
			"בני דרום",
			"בני ראם",
			"בניה",
			"גבעת ברנר",
			"גבעת וושינגטון",
			"גדרה",
			"גיבתון",
			"גן הדרום",
			"גן שלמה",
			"גני טל",
			"חפץ חיים",
			"יבנה",
			"יד בנימין",
			"יסודות",
			"כפר אביב",
			"כפר מרדכי",
			"כרם ביבנה",
			"מזכרת בתיה",
			"מישר",
			"מעון צופיה",
			"משגב דב",
			"מתחם בני דרום",
			"ניר גלים",
			"נצר חזני",
			"עשרת",
			"קבוצת יבנה",
			"קדרון",
			"קריית עקרון",
			"שדמה",
			"Kfar Hassidim",
			"אורנים",
			"אושה",
			"אזור תעשייה שער נעמן",
			"איבטין",
			"אל-ח'וואלד מערב",
			"בית עלמין תל רגב",
			"בסמת טבעון",
			"ח'וואלד",
			"יגור",
			"כפר ביאליק",
			"כפר המכבי",
			"כפר חסידים",
			"כפר תקווה",
			"נופית",
			"קריית ביאליק",
			"קריית טבעון",
			"קריית ים",
			"קריית מוצקין",
			"קרית אתא",
			"ראס עלי",
			"רכסים",
			"רמת יוחנן",
			"שער העמקים",
			"Kerem BenShemen",
			"אזור תעשייה נשר - רמלה",
			"אחיסמך",
			"אחיעזר",
			"אירוס",
			"באר יעקב",
			"בית דגן",
			"בית חנן",
			"בית חשמונאי",
			"בית עובד",
			"בית עוזיאל",
			"בן שמן",
			"גאליה",
			"גזר",
			"גינתון",
			"גמזו",
			"גן שורק",
			"גנות",
			"גני הדר",
			"גני יוחנן",
			"זיתן",
			"חולדה",
			"חמד",
			"יגל",
			"יד רמב''ם",
			"יציץ",
			"ישרש",
			"כפר ביל''ו",
			"כפר בן נון",
			"כפר דניאל",
			"כפר הנגיד",
			"כפר חב''ד",
			"כפר נוער בן שמן",
			"כפר רות",
			"כפר שמואל",
			"כרמי יוסף",
			"לוד",
			"לפיד",
			"מבוא מודיעים",
			"מודיעין",
			"מודיעין - ישפרו סנטר",
			"מודיעין - ליגד סנטר",
			"מצליח",
			"משמר איילון",
			"משמר דוד",
			"משמר השבעה",
			"נוף איילון",
			"נטעים",
			"ניר צבי",
			"נס ציונה",
			"נען",
			"נצר סרני",
			"סתריה",
			"עזריה",
			"עיינות",
			"פארק תעשיות פלמחים",
			"פדיה",
			"פלמחים",
			"פתחיה",
			"צפריה",
			"ראשון לציון - מזרח",
			"ראשון לציון - מערב",
			"רחובות",
			"רמות מאיר",
			"רמלה",
			"שילת",
			"שעלבים",
			"תעשיון צריפין",
			"אום אל פחם",
			"אום אל קוטוף",
			"אל עריאן",
			"באקה אל גרבייה",
			"בסמ\"ה",
			"ברטעה",
			"ברקאי",
			"ג'ת",
			"חריש",
			"כפר קרע",
			"להבות חביבה",
			"מגל",
			"מועאוויה",
			"מי עמי",
			"מייסר",
			"מעלה עירון",
			"מצפה אילן",
			"מצר",
			"עין אל-סהלה",
			"ערערה",
			"קציר",
			"אזור תעשייה ניר עציון",
			"בית צבי",
			"בת שלמה",
			"גבע כרמל",
			"דור",
			"הבונים",
			"כפר הנוער ימין אורד",
			"כרם מהר''ל",
			"מאיר שפיה",
			"מגדים",
			"מרכז מיר''ב",
			"נווה ים",
			"נחשולים",
			"ניר עציון",
			"עופר",
			"עין איילה",
			"עין הוד",
			"עין חוד",
			"עין כרמל",
			"עתלית",
			"פוריידיס",
			"צרופה",
			"החותרים",
			"חיפה - כרמל ועיר תחתית",
			"חיפה - מערב",
			"חיפה - מפרץ והקריות",
			"חיפה - נווה שאנן ורמות כרמל",
			"טירת כרמל",
			"כפר גלים",
			"נשר",
			"אביחיל",
			"אזור תעשייה טירה",
			"אזור תעשייה עמק חפר",
			"אחיטוב",
			"אייל",
			"אליכין",
			"אלישיב",
			"אמץ",
			"בארותיים",
			"בורגתה",
			"בחן",
			"בית הלוי",
			"בית חזון",
			"בית חרות",
			"בית ינאי",
			"בית יצחק - שער חפר",
			"ביתן אהרן",
			"בני דרור",
			"בת חן",
			"בת חפר",
			"גאולי תימן",
			"גאולים",
			"גבעת חיים איחוד",
			"גבעת חיים מאוחד",
			"גבעת שפירא",
			"גן יאשיה",
			"גנות הדר",
			"הדר עם",
			"המעפיל",
			"המרכז האקדמי רופין",
			"העוגן",
			"זמר",
			"חבצלת השרון וצוקי ים",
			"חגלה",
			"חופית",
			"חיבת ציון",
			"חניאל",
			"חרב לאת",
			"חרות",
			"טייבה",
			"טירה",
			"יד חנה",
			"ינוב",
			"יעף",
			"כפר הס",
			"כפר הרא''ה",
			"כפר ויתקין",
			"כפר חיים",
			"כפר ידידיה",
			"כפר יונה",
			"כפר יעבץ",
			"כפר מונש",
			"כפר עבודה",
			"מכמורת",
			"מעברות",
			"משמר השרון",
			"משמרת",
			"נורדיה",
			"ניצני עוז",
			"נעורים",
			"עולש",
			"עזריאל",
			"עין החורש",
			"עין ורד",
			"עין שריד",
			"פורת",
			"פרדסיה",
			"צוקי ים וחבצלת השרון",
			"צור יצחק",
			"צור משה",
			"צור נתן",
			"צורן",
			"קדימה",
			"קלנסווה",
			"רמת הכובש",
			"שושנת העמקים",
			"שער אפרים",
			"תל מונד",
			"תנובות",
			"אדורה",
			"אזור תעשייה מיתרים",
			"אלון",
			"אלון שבות",
			"אליאב",
			"אלעזר",
			"אמציה",
			"אפרת",
			"אשכולות",
			"בית חגי",
			"בית יתיר",
			"ביתר עילית",
			"בני דקלים",
			"בת עין",
			"גבעות",
			"הר גילה",
			"הר עמשא",
			"חברון",
			"חוות שדה בר",
			"טנא עומרים",
			"כפר אדומים",
			"כפר אלדד",
			"כפר עציון",
			"כרמי צור",
			"כרמי קטיף",
			"כרמל",
			"מגדל עוז",
			"מיצד",
			"מעון",
			"מעלה אדומים",
			"מעלה חבר",
			"מעלה עמוס",
			"מצפה יריחו",
			"נגוהות",
			"נווה דניאל",
			"נופי פרת",
			"נוקדים",
			"נטע",
			"סוסיה",
			"סנסנה",
			"עלמון",
			"עתניאל",
			"פני קדם",
			"קדר",
			"קרית ארבע",
			"ראש צורים",
			"שמעה",
			"שני ליבנה",
			"שקף",
			"תלם",
			"תקוע",
			"אבנת",
			"אלמוג",
			"בית הערבה",
			"בתי מלון ים המלח",
			"ורד יריחו",
			"מלונות ים המלח מרכז",
			"מצדה",
			"מצוקי דרגות",
			"מצפה שלם",
			"מרחצאות עין גדי",
			"נאות הכיכר",
			"נווה זוהר",
			"עין בוקק",
			"עין גדי",
			"עין תמר",
			"קליה",
			"בית אורן",
			"גבעת וולפסון",
			"דלית אל כרמל",
			"יערות הכרמל",
			"כלא דמון",
			"עספיא",
			"Ramat Rachel",
			"גבעת זאב",
			"ירושלים - אזור תעשייה עטרות",
			"ירושלים - מזרח, מרכז ומערב",
			"ירושלים - צפון ואלונים",
			"ירושלים - רובע אורנים",
			"ירושלים - רובע דרום",
			"אזור תעשייה אפק ולב הארץ",
			"אלעד",
			"בארות יצחק",
			"בית נחמיה",
			"בית עריף",
			"בני עטרות",
			"ברקת",
			"גבעת השלושה",
			"גבעת כ''ח",
			"גת רימון",
			"חדיד",
			"טירת יהודה",
			"כפר טרומן",
			"כפר סירקין",
			"מגשימים",
			"מזור",
			"מעש",
			"נופך",
			"נחלים",
			"נחשונים",
			"עינת",
			"פתח תקווה",
			"ראש העין",
			"רינתיה",
			"שהם",
			"תעשיון חצב",
			"אביגדור",
			"אבן שמואל",
			"אורות",
			"אזור תעשייה כנות",
			"אזור תעשייה עד הלום",
			"אזור תעשייה תימורים",
			"אחווה",
			"אחוזם",
			"איתן",
			"אל עזי",
			"אלומה",
			"אמונים",
			"אשדוד - א,ב,ד,ה",
			"אשדוד - אזור תעשייה צפוני ונ",
			"אשדוד - ג,ו,ז",
			"אשדוד - ח,ט,י,יג,יד,טז",
			"אשדוד - יא,יב,טו,יז,מרינה",
			"באר טוביה",
			"ביצרון",
			"בית גוברין",
			"בית ניר",
			"בית עזרא",
			"בני עי''ש",
			"גבעתי",
			"גלאון",
			"גן יבנה",
			"גת",
			"ורדון",
			"זבדיאל",
			"זוהר",
			"זרחיה",
			"חצב",
			"חצור",
			"יד נתן",
			"ינון",
			"כנות",
			"כפר אחים",
			"כפר הרי''ף וצומת ראם",
			"כפר ורבורג",
			"כפר מנחם",
			"לכיש",
			"מנוחה",
			"מרכז שפירא",
			"משואות יצחק",
			"נגבה",
			"נהורה",
			"נוגה",
			"נווה מבטח",
			"נועם",
			"נחלה",
			"ניר בנים",
			"ניר ח''ן",
			"סגולה",
			"עוזה",
			"עוצם",
			"עזר",
			"עזריקם",
			"עין צורים",
			"ערוגות",
			"פארק תעשייה ראם",
			"קדמה",
			"קוממיות",
			"קריית גת, כרמי גת",
			"קריית מלאכי",
			"רבדים",
			"רווחה",
			"שדה דוד",
			"שדה יואב",
			"שדה משה",
			"שדה עוזיהו",
			"שחר",
			"שלווה",
			"שפיר",
			"שתולים",
			"תימורים",
			"תלמי יחיאל",
			"תלמים",
			"אביאל",
			"אור עקיבא",
			"אזור תעשייה יקנעם עילית",
			"אזור תעשייה מבוא כרמל",
			"אזור תעשייה קיסריה",
			"אזור תעשייה רגבים",
			"אלוני יצחק",
			"אליקים",
			"בית חנניה",
			"בית סוהר מגידו",
			"בית ספר אורט בנימינה",
			"בנימינה",
			"גבעת חביבה",
			"גבעת ניל''י",
			"גבעת עדה",
			"גבעת עוז",
			"גלעד - אבן יצחק",
			"גן השומרון",
			"גן שמואל",
			"ג'סר א-זרקא",
			"דליה",
			"הזורע ויקנעם המושבה",
			"זכרון יעקב",
			"חדרה - מזרח",
			"חדרה - מערב",
			"חדרה - מרכז",
			"חדרה - נווה חיים",
			"יקנעם המושבה והזורע",
			"יקנעם עילית",
			"כפר גליקסון",
			"כפר פינס",
			"כרכור",
			"מאור",
			"מגידו",
			"מדרך עוז",
			"מעגן מיכאל",
			"מעיין צבי",
			"מענית",
			"מרכז ימי קיסריה",
			"משמר העמק",
			"משמרות",
			"עין העמק",
			"עין השופט",
			"עין עירון",
			"עין שמר",
			"עמיקם",
			"פרדס חנה",
			"קיסריה",
			"רגבים",
			"רמות מנשה",
			"רמת הנדיב",
			"רמת השופט",
			"שדה יצחק",
			"שדות ים",
			"שער מנשה",
			"תלמי אלעזר",
			"אופקים",
			"אורים",
			"אשבול",
			"אשל הנשיא",
			"בטחה",
			"בית הגדי",
			"ברור חיל",
			"ברוש",
			"גבולות",
			"גבעולים מעגלים מלילות",
			"גילת",
			"דורות",
			"זרועה",
			"חוות שיקמים",
			"יושיביה",
			"מבועים",
			"מלילות גבעולים מעגלים",
			"מסלול",
			"מעגלים גבעולים מלילות",
			"ניר משה",
			"ניר עקיבא",
			"נתיבות",
			"פדויים",
			"פטיש",
			"פעמי תש''ז",
			"צאלים",
			"קלחים",
			"קרית חינוך מרחבים",
			"רוחמה",
			"רנן",
			"שבי דרום",
			"שדה צבי",
			"שיבולים",
			"שרשרת",
			"תאשור",
			"תדהר",
			"תלמי ביל''ו",
			"תפרח",
			"Nitzan",
			"אזור תעשייה הדרומי אשקלון",
			"אזור תעשייה צפוני אשקלון",
			"אשקלון",
			"באר גנים",
			"בית שקמה",
			"ברכיה",
			"בת הדר",
			"גיאה",
			"הודיה",
			"חלץ",
			"כוכב מיכאל",
			"כפר סילבר",
			"מבקיעים",
			"משען",
			"ניצן",
			"ניצנים",
			"ניר ישראל",
			"תלמי יפה",
			"אזור תעשייה עידן הנגב",
			"באר שבע - דרום",
			"באר שבע - מזרח",
			"באר שבע - מערב",
			"באר שבע - צפון",
			"בית קמה",
			"גבעות בר",
			"דביר",
			"חצרים",
			"כרמים",
			"כרמית",
			"להב",
			"להבים",
			"לקיה והפזורה",
			"מיתר",
			"משמר הנגב",
			"נאות חובב",
			"נבטים",
			"עומר",
			"רהט והפזורה",
			"שובל",
			"שומריה",
			"תראבין א-צאנע ופזורה",
			"Kfar Maimon and Tushia",
			"אבשלום",
			"אוהד וצוחר",
			"אור הנר",
			"איבים, שדרות",
			"ארז",
			"בארי",
			"בני נצרים",
			"גבים, מכללת ספיר",
			"גברעם",
			"דקל",
			"זיקים",
			"זמרת ושובה",
			"חולית",
			"יבול",
			"יד מרדכי",
			"יכיני",
			"ישע, מבטחים, עמיעוז",
			"יתד",
			"כיסופים",
			"כפר מימון ותושיה",
			"כפר עזה",
			"כרם שלום",
			"כרמיה",
			"מבטחים עמיעוז ישע",
			"מגן",
			"מטווח ניר עם",
			"מפלסים",
			"נווה",
			"נחל עוז",
			"ניר יצחק",
			"ניר עוז",
			"ניר עם",
			"נירים",
			"נתיב העשרה",
			"סופה",
			"סעד",
			"עין הבשור",
			"עין השלושה",
			"עלומים",
			"עמיעוז, מבטחים, ישע",
			"פרי גן",
			"צוחר ואוהד",
			"רעים",
			"שדה אברהם",
			"שדה ניצן",
			"שדרות, איבים",
			"שובה וזמרת",
			"שוקדה",
			"שלומית",
			"תלמי אליהו",
			"תלמי יוסף",
			"תקומה",
			"תקומה וחוות יזרעם",
			"אליפז ומכרות תמנע",
			"באר אורה",
			"גרופית",
			"חוות ערנדל",
			"חי-בר יטבתה",
			"חצבה",
			"יהל",
			"יטבתה",
			"כושי רמון",
			"לוטן",
			"נאות סמדר",
			"נווה חריף",
			"סמר",
			"ספיר",
			"עידן",
			"עין חצבה",
			"עין יהב",
			"עיר אובות",
			"פארן",
			"צופר",
			"צוקים",
			"קטורה",
			"שחרות",
			"שיטים",
			"Peki'in HaHadasha",
			"אביבים",
			"אבירים",
			"אבן מנחם",
			"אדמית",
			"אזור תעשייה אכזיב מילואות",
			"אזור תעשייה רמת דלתון",
			"אילון",
			"אלקוש",
			"בית הלל",
			"בית ספר שדה מירון",
			"בן עמי",
			"בצת",
			"ברעם",
			"גונן",
			"גורן",
			"געתון",
			"גרנות הגליל",
			"ג'ש - גוש חלב",
			"גשר הזיו",
			"דוב''ב",
			"דישון",
			"דלתון",
			"דן",
			"דפנה",
			"הגושרים",
			"הילה",
			"זרעית",
			"חוסן",
			"חורפיש",
			"חניתה",
			"יובל",
			"יחיעם",
			"יערה",
			"יפתח",
			"יראון",
			"כברי",
			"כפר בלום",
			"כפר גלעדי",
			"כפר ורדים",
			"כפר סאלד",
			"כרם בן זמרה",
			"להבות הבשן",
			"לימן",
			"מטולה",
			"מלכיה",
			"מנות",
			"מנרה",
			"מעונה",
			"מעיין ברוך",
			"מעיליא",
			"מעלות תרשיחא",
			"מצובה",
			"מרגליות",
			"משגב עם",
			"מתת",
			"נאות מרדכי",
			"נהריה",
			"נווה זיו",
			"נטועה",
			"סאסא",
			"סער",
			"עבדון",
			"עברון",
			"עג'ר",
			"עין יעקב",
			"עלמה",
			"עמיר",
			"ערב אל עראמשה",
			"פסוטה",
			"פקיעין",
			"צבעון",
			"צוריאל",
			"קרית שמונה",
			"ראש הנקרה",
			"ריחאנייה",
			"רמות נפתלי",
			"שאר ישוב",
			"שבי ציון",
			"שדה נחמיה",
			"שומרה",
			"שלומי",
			"שמיר",
			"שניר",
			"שתולה",
			"תל חי",
			"אלמגור",
			"אניעם",
			"גבעת אבני",
			"האון",
			"חד נס",
			"כנף",
			"כפר קיש",
			"מסדה",
			"מעגן",
			"מעלה גמלא",
			"עין גב",
			"קדמת צבי",
			"קלע",
			"קצרין",
			"קצרין - אזור תעשייה",
			"רמות",
			"שעל",
			"שער הגולן",
			"תל קציר",
			"Giv'on HaHadasha",
			"אבני חפץ",
			"אורנית",
			"אזור תעשייה בראון",
			"אזור תעשייה שער בנימין",
			"אחיה",
			"איתמר",
			"אלון מורה",
			"אלפי מנשה",
			"אלקנה",
			"אריאל",
			"בית אל",
			"בית אריה",
			"בית חורון",
			"ברוכין",
			"ברקן",
			"גבע בנימין",
			"גני מודיעין",
			"דולב",
			"הר ברכה",
			"חוות יאיר",
			"חיננית",
			"חלמיש",
			"חרמש",
			"חרשה",
			"חשמונאים",
			"טל מנשה",
			"טלמון",
			"יצהר",
			"יקיר",
			"כוכב השחר",
			"כוכב יאיר - צור יגאל",
			"כוכב יעקב",
			"כפר האורנים",
			"כפר תפוח",
			"מבוא דותן",
			"מבוא חורון",
			"מגדלים",
			"מגרון",
			"מודיעין עילית",
			"מעלה לבונה",
			"מעלה מכמש",
			"מעלה שומרון",
			"מתתיהו",
			"נבי סמואל",
			"נופי נחמיה",
			"נופים",
			"נחליאל",
			"ניל''י",
			"נעלה",
			"נריה",
			"סלעית",
			"עדי עד",
			"עופרים",
			"עטרת",
			"עלי",
			"עלי זהב",
			"עמיחי",
			"עמנואל",
			"ענב",
			"עפרה",
			"עץ אפרים",
			"פדואל",
			"פסגות",
			"צופין",
			"קדומים",
			"קידה",
			"קריית נטפים",
			"קרני שומרון",
			"רבבה",
			"רחלים",
			"ריחן",
			"רימונים",
			"שבות רחל",
			"שבי שומרון",
			"שילה",
			"שערי תקווה",
			"שקד",
			"תל ציון",
			"אבן יהודה",
			"אודים",
			"אלישמע",
			"ארסוף",
			"בית ברל",
			"בית יהושע",
			"בית סוהר השרון",
			"בני ציון",
			"בצרה",
			"גבעת חן",
			"ג'לג'וליה",
			"גן חיים",
			"גני עם",
			"געש",
			"הוד השרון",
			"הרצליה - גליל ים ומרכז",
			"הרצליה - מרכז וגליל ים",
			"הרצליה - פיתוח",
			"חגור",
			"חורשים",
			"חרוצים",
			"יקום",
			"ירחיב",
			"ירקונה",
			"כפר ברא",
			"כפר מל''ל",
			"כפר נטר",
			"כפר סבא",
			"כפר קאסם",
			"כפר שמריהו",
			"מכון וינגייט",
			"מתן",
			"נווה ימין",
			"נווה ירק",
			"ניר אליהו",
			"נירית",
			"נתניה - מזרח",
			"נתניה - מערב",
			"עדנים",
			"צופית",
			"רמות השבים",
			"רמת השרון",
			"רעננה",
			"רשפון",
			"שדה ורבורג",
			"שדי חמד",
			"שפיים",
			"תל יצחק",
			"Adirim",
			"Dvora",
			"Ein Harod (Ihud)",
			"Gadish",
			"Meitav",
			"Meitav",
			"Merkaz Hever",
			"Merkaz Omen",
			"Mle'a",
			"Nir Yafeh",
			"Prazon",
			"Yael",
			"אום אל-גנם",
			"אזור תעשייה מבואות הגלבוע",
			"אחוזת ברק",
			"אכסאל",
			"אלון הגליל",
			"אלוני אבא",
			"אלונים",
			"אתר ההנצחה גולני",
			"בית זייד",
			"בית לחם הגלילית",
			"בית סוהר שיטה וגלבוע",
			"בית שערים",
			"בלפוריה",
			"גבע",
			"גבעת אלה",
			"גבת",
			"גדעונה",
			"גזית",
			"גן נר",
			"גניגר",
			"דבוריה",
			"דברת",
			"דחי",
			"הושעיה",
			"היוגב",
			"הסוללים",
			"הרדוף",
			"ואדי אל חמאם",
			"זרזיר",
			"חג'אג'רה",
			"חנתון",
			"טורעאן",
			"טייבה בגלבוע",
			"טמרה בגלבוע",
			"יזרעאל",
			"יפיע",
			"יפעת",
			"ישובי אמן",
			"ישובי חבר",
			"ישובי יעל",
			"ישובי יעל.",
			"כעביה",
			"כעביה טבאש",
			"כעביה-טבאש-חג'אג'רה",
			"כפר ברוך",
			"כפר גדעון",
			"כפר החורש",
			"כפר טבאש",
			"כפר יהושע",
			"כפר יחזקאל",
			"כפר כנא",
			"כפר מיסר",
			"כפר נהר הירדן",
			"כפר תבור",
			"מגדל העמק",
			"מגן שאול",
			"מוקייבלה",
			"מזרע",
			"מנשית זבדה",
			"מרחביה מושב",
			"מרחביה קיבוץ",
			"משהד",
			"נאעורה",
			"נהלל",
			"נורית",
			"נין",
			"נצרת",
			"נצרת עילית (נוף הגליל)",
			"סואעד חמירה",
			"סולם",
			"סנדלה",
			"עדי",
			"עוזייר",
			"עילוט",
			"עין דור",
			"עין חרוד",
			"עין מאהל",
			"עפולה",
			"ציפורי",
			"רומאנה",
			"רומת אל הייב",
			"ריינה",
			"רם און",
			"רמת דוד",
			"רמת ישי",
			"רמת צבי",
			"שבלי",
			"שדה יעקב",
			"שמשית",
			"שריד",
			"תל יוסף",
			"תל עדשים",
			"תמרת"
	))),
	EN(new HashSet<>(Arrays.asList(
			"Ardanel Ranch",
			"Be'er Ora",
			"Ein Hatzeva",
			"Ein Yahav",
			"Elipaz and Timna Mines",
			"Grofit",
			"Hatzeva",
			"Idan",
			"Ir Ovot",
			"Ktura",
			"Kushi Rimon",
			"Lotan",
			"Neot Smadar",
			"Neveh Harif",
			"Paran",
			"Samar",
			"Sapir",
			"Shachrut",
			"Shitim",
			"Tzofar",
			"Tzukim",
			"Yahel",
			"Yotvata",
			"Yotvata Hai Bar Nature Reserve",
			"Beit Alfa and Heftziba",
			"Beit HaShita",
			"Beit She'an",
			"Beit Yossef",
			"Ein HaNatziv",
			"Gesher",
			"Hamadia",
			"Havat Eden",
			"Heftziba and Beit Alfa",
			"Kfar Ruppin",
			"Ma'aleh Gilboa",
			"Maoz Haim",
			"Menahemia",
			"Merav",
			"Messilot",
			"Mlkishua Rehabilitation Village",
			"Moledet",
			"Neveh Eitan",
			"Neveh Or",
			"Nir David",
			"Rechov",
			"Reshafim",
			"Revaya",
			"Sdeh Eliyahu",
			"Sdeh Nachum",
			"Sdei Trumot",
			"Shlafim",
			"Shluchot",
			"Tel Teomim",
			"Tirat Zvi",
			"Yardena",
			"Zvaim Industrial Zone",
			"Abu Ghosh",
			"Aderet",
			"Agur",
			"Aminadav",
			"Aviezer",
			"Bar Giora",
			"Beit Meir",
			"Beit Nekofa",
			"Beit Shemesh",
			"Beit Zayit",
			"Beko'a",
			"Brosh Industrial Zone",
			"Ein Naqquba",
			"Ein Rafa",
			"Eshtaol",
			"Even Sapir",
			"Geffen",
			"Givat Ishayahu",
			"Givat Yearim",
			"Giv'ot Eden",
			"Gizo",
			"Har Adar",
			"Har Tuv - Tzora Industrial Zone",
			"Harel",
			"Kfar Uriah",
			"Kfar Zoharim",
			"Kiryat Anavim",
			"Kiryat Yearim",
			"Ksalon",
			"Latrun",
			"Luzit",
			"Ma'aleh HaHamisha",
			"Mahsiya",
			"Mata",
			"Mesillat Zion",
			"Mevasseret Zion",
			"Mevo Beitar",
			"Motza Illit",
			"Nachshon",
			"Naham",
			"Nataf",
			"Nehusha",
			"Ness Harim",
			"Netiv HaLamed-Heh",
			"Neveh Ilan",
			"Neveh Michael (Rogalit)",
			"Neveh Shalom",
			"Ora",
			"Ramat Raziel",
			"Retorno - Givat Shesh",
			"Sdot Micha",
			"Shoeva",
			"Shoresh",
			"Srigim (Li-On)",
			"Tal Shachar",
			"Taoz",
			"Tarom",
			"Tirosh",
			"Tzafririm",
			"Tzalfon",
			"Tzora",
			"Tzuba",
			"Tzur Hadassa",
			"Yad HaShmona",
			"Yish'i",
			"Zanoah",
			"Zekharia",
			"Beer Sheva - East",
			"Beer Sheva - North",
			"Beer Sheva - South",
			"Beer Sheva - West",
			"Beit Kama",
			"Carmit",
			"Dvir",
			"Giv'ot Bar",
			"Hatzerim",
			"Idan HaNegev Industrial Zone",
			"Kramim",
			"Lahav",
			"Lakiya and the Bedouin Diaspora",
			"Lehavim",
			"Meitar",
			"Mishmar HaNegev",
			"Neot Hovav",
			"Nevatim",
			"Omer",
			"Rahat and the Bedouin Diaspora",
			"Shomria",
			"Shoval",
			"Tirabin al-Sana and the Bedouin Diaspora",
			"Abirim",
			"Achziv Miluot Industrial Zone",
			"Alkosh",
			"Alma",
			"Amir",
			"Arab al-Aramshe",
			"Avdon",
			"Avivim",
			"Baram",
			"Beit Hillel",
			"Ben Ami",
			"Betzet",
			"Cabri",
			"Dafna",
			"Dalton",
			"Dan",
			"Dishon",
			"Dovev",
			"Eilon",
			"Ein Yacov",
			"Even Menachem",
			"Evron",
			"Fassuta",
			"Ga'aton",
			"Gesher HaZiv",
			"Ghajar",
			"Gonen",
			"Goren",
			"Gornot HaGalil",
			"HaGoshrim",
			"Hanita",
			"Hila",
			"Hossen",
			"Hurfeish",
			"Idmit",
			"Iftach",
			"Jish (Gush Halav)",
			"Kerem Ben Zimra",
			"Kfar Blum",
			"Kfar Giladi",
			"Kfar Szold",
			"Kfar Vradim",
			"Kiryat Shmona",
			"Lehavot HaBashan",
			"Lehman",
			"Ma'a lot Tarshicha",
			"Ma'ayan Baruch",
			"Malkia",
			"Manara",
			"Manot",
			"Maona",
			"Margaliot",
			"Matat",
			"Metulla",
			"Metzuba",
			"Mi'ilya",
			"Misgav Am",
			"Nahariya",
			"Neot Mordechai",
			"Netua",
			"Neveh Ziv",
			"Peki'in",
			"Ramat Dalton Industrial Zone",
			"Ramot Naftali",
			"Rehaniya",
			"Rosh HaNikra",
			"Sa'ar",
			"Sassa",
			"Sdeh Meron School",
			"Sdeh Nechemia",
			"Shamir",
			"Shavei Zion",
			"Shear Yeshuv",
			"Shlomi",
			"Shomera",
			"Shtula",
			"Snir",
			"Tel Hai",
			"Tzuriel",
			"Ya'ara",
			"Yechiam",
			"Yir'on",
			"Yuval",
			"Zarit",
			"Zivon",
			"פקיעין החדשה",
			"Azor",
			"Bat Yam",
			"Bnei Brak",
			"Ganei Tikva",
			"Givat Shmuel",
			"Givatayim",
			"Holon",
			"Kiryat Ono",
			"Mikveh Israel",
			"Or Yehuda",
			"Ramat Gan - East",
			"Ramat Gan - West",
			"Savyon",
			"Tel Aviv - Across the Yarkon",
			"Tel Aviv - City Center",
			"Tel Aviv - East",
			"Tel Aviv - South and Jaffa",
			"Yehud-Monosson",
			"Almog",
			"Avnat",
			"Beit HaArava",
			"Dead Sea Hotels",
			"Dead Sea Hotels - Center",
			"Ein Bokek",
			"Ein Gedi",
			"Ein Gedi Baths",
			"Ein Tamar",
			"Kalia",
			"Massada",
			"Metzokei Dragot",
			"Mitzpeh Shalem",
			"Neot HaKikar",
			"Neveh Zohar",
			"Vered Yericho",
			"Eilat",
			"Eilot",
			"Shchoret Industrial Zone",
			"Alumim",
			"Amioz Mivtachim Yesha",
			"Avshalom",
			"Be'eri",
			"Bnei Netzarim",
			"Dekel",
			"Ein HaBsor",
			"Ein HaShlosha",
			"Erez",
			"Gavim, Sapir College",
			"Gvaram",
			"Holit",
			"Ibim Sderot",
			"Karmia",
			"Kerem Shalom",
			"Kfar Azza",
			"Kfar Maimon and Tushia",
			"Kissufim",
			"Magen",
			"Mefalsim",
			"Mivtachim Amioz Yesha",
			"Nachal Oz",
			"Naveh",
			"Netiv HaAssara",
			"Nir Am",
			"Nir Itzhak",
			"Nir Oz",
			"Nir- Um shooting range",
			"Nirim",
			"Ohad Tzohar",
			"Or HaNer",
			"Pri Gan",
			"Reim",
			"Sa'ad",
			"Sdeh Avraham",
			"Sdeh Nitzan",
			"Sderot, Ibim",
			"Shlomit",
			"Shokeda",
			"Shuva and Zimrat",
			"Sufa",
			"Talmei Eliyahu",
			"Talmei Yossef",
			"Tkuma",
			"Tkuma and Havat Izra'am",
			"Tzohar and Ohad",
			"Yad Mordechai",
			"Yakhini",
			"Yated",
			"Yesha Mivtachim Amioz",
			"Yevul",
			"Zikim",
			"Zimrat and Shuva",
			"כפר מימון ותושיה",
			"Afik",
			"Alonei HaBashan",
			"Avnei Eitan",
			"Bnei Yehuda and Givat Yoav",
			"Bnei Yehuda Industrial Zone",
			"Buq'ata",
			"Ein Quiniyye",
			"Ein Zivan",
			"El Rom",
			"Eliad",
			"Givat Yoav and Bnei Yehuda",
			"Gshur",
			"Hamat gader",
			"Haspin",
			"Keshet",
			"Kfar Haruv",
			"Majdal Shams",
			"Mas'ade",
			"Merom Golan",
			"Metzar",
			"Mevo Hama",
			"Natur",
			"Neot Golan",
			"Neveh Ativ",
			"Nimrod",
			"Nov",
			"Odem",
			"Ortal",
			"Ramat Magshimim",
			"Yonatan",
			"HaHotrim",
			"Haifa - Carmel and Lower City",
			"Haifa - Krayot and Bay",
			"Haifa - Ramot HaCarmel and Neveh Sha'anan",
			"Haifa - West",
			"Kfar Galim",
			"Nesher",
			"Tirat Carmel",
			"Al Khawaled - West",
			"Basmat Tab'un",
			"Ibtin",
			"Kfar Biyalik",
			"Kfar HaMaccabi",
			"Kfar Hassidim",
			"Kfar Tikva",
			"Khawaled",
			"Kiryat Atta",
			"Kiryat Biyalik",
			"Kiryat Motzkin",
			"Kiryat Tivon",
			"Kiryat Yam",
			"Nofit",
			"Oranim",
			"Ramat Yochana",
			"Ras Ali",
			"Rechasim",
			"Sha'ar HaAmakim",
			"Sha'ar Na'aman Industrial Zone",
			"Tel Regev Cemetary",
			"Usha",
			"Yagur",
			"כפר חסידים",
			"Ahituv",
			"Amatz",
			"Avihail",
			"Azriel",
			"Bahan",
			"Bat Chen",
			"Bat Hefer",
			"Be'erotaim",
			"Beit HaLevi",
			"Beit Hazon",
			"Beit Herut",
			"Beit Yannai",
			"Beit Yithak - Sha'ar Hefer",
			"Bitan Aharon",
			"Bnei Dror",
			"Burgata",
			"Ein HaHoresh",
			"Ein Sarid",
			"Ein Vered",
			"Elyachin",
			"Elyashiv",
			"Emek Heffer Industrial Zone",
			"Eyal",
			"Gan Yoshia",
			"Geulei Teiman",
			"Geulim",
			"Ginot Hadar",
			"Givat Haim (Ihud)",
			"Givat Haim (Meuhad)",
			"Givat Shapira",
			"Hadar Am",
			"HaMa'apil",
			"Haniel",
			"HaOgen",
			"Havatzelet HaSharon and Tzukei Yam",
			"Herev Le'Et",
			"Herut",
			"Hibat Zion",
			"Hofit",
			"Hogla",
			"Kadima",
			"Kfar Avoda",
			"Kfar Haim",
			"Kfar HaRoeh",
			"Kfar Hess",
			"Kfar Monash",
			"Kfar Vitkin",
			"Kfar Yavetz",
			"Kfar Yedidia",
			"Kfar Yona",
			"Ma'abarot",
			"Mikhmoret",
			"Mishmar HaSharon",
			"Mishmeret",
			"Neurim",
			"Nitzanei Oz",
			"Nordia",
			"Olesh",
			"Pardessiya",
			"Porat",
			"Qalansawe",
			"Ramat HaKovesh",
			"Ruppin Academic Center",
			"Sha'ar Efraim",
			"Shoshanat Ha'Amakim",
			"Tayibe",
			"Tel Mond",
			"Tira",
			"Tira Industrial Area",
			"Tnuvot",
			"Tzoran",
			"Tzukei Yam and Havatzelet HaSharon",
			"Tzur Itzhak",
			"Tzur Moshe",
			"Tzur Natan",
			"Ya'af",
			"Yad Hana",
			"Yanuv",
			"Zemer",
			"Atlit",
			"Bat Shlomo",
			"Beit Zvi",
			"Dor",
			"Ein Ayala",
			"Ein Carmel",
			"Ein Chod",
			"Ein Hod",
			"Fureidis",
			"Geva Carmel",
			"HaBonim",
			"Kerem Maharal",
			"Megadim",
			"Meir Shfeya",
			"Merav Center",
			"Nachsholim",
			"Neveh Yam",
			"Nir Etzion",
			"Nir Etzion Industrial Area",
			"Ofer",
			"Tzrufa",
			"Yemin Orde Youth Village",
			"Givat Ze'ev",
			"Jerusalem - Atarot Industrial Zone",
			"Jerusalem - East, Center and West",
			"Jerusalem - North and Alonim",
			"Jerusalem - Oranim Quarter",
			"Jerusalem - Southern Quarter",
			"רמת רחל",
			"Adora",
			"Almon",
			"Alon",
			"Alon Shvut",
			"Amatzia",
			"Bat Ayin",
			"Beit Hagai",
			"Beit Yatir",
			"Beitar Illit",
			"Bnei Dkalim",
			"Carmel",
			"Efrat",
			"Elazar",
			"Eliav",
			"Eshkolot",
			"Gvaot",
			"Har Amsha",
			"Har Gilo",
			"Havat Sdeh Bar",
			"Hebron",
			"Kadarim",
			"Karmei Katif",
			"Karmei Tzur",
			"Kfar Edomim",
			"Kfar Eldad",
			"Kfar Etzion",
			"Kiryat Arba",
			"Ma'ale Hever",
			"Ma'aleh Amos",
			"Ma'aleh Edomim",
			"Ma'on",
			"Meitarim Industrial Zone",
			"Metzad",
			"Migdal Oz",
			"Mitzpeh Yericho",
			"Negohot",
			"Neta",
			"Neveh Daniel",
			"Nofei Prat",
			"Nokdim",
			"Otniel",
			"Pnei Kedem",
			"Rosh Tzurim",
			"Sansana",
			"Shekef",
			"Sheni LeYavne",
			"Shim'a",
			"Susya",
			"Telem",
			"Teneh Omarim",
			"Tko'a",
			"Almagor",
			"Aniam",
			"Ein Gev",
			"Giv'at Avni",
			"Had Ness",
			"Ha'On",
			"Kanaf",
			"Katzrin",
			"Katzrin - Industrial Area",
			"Kela",
			"Kfar Kish",
			"Kidmat Zvi",
			"Ma'agan",
			"Ma'aleh Gamla",
			"Masada",
			"Ramot",
			"Sha'al",
			"Sha'ar HaGolan",
			"Tel Katzir",
			"Achva",
			"Ad Halom Industrial Zone",
			"Ahuzam",
			"Al Azi",
			"Aluma",
			"Arugot",
			"Ashdod - Alef, Bet, Dalet, Heh",
			"Ashdod - Gimmel, Vav, Zain",
			"Ashdod - Het, Tet, Yod, Yod Gimmel, Yod Dalet, Te*",
			"Ashdod - Northern Industrial Zone and port",
			"Ashdod - Yod Alef, Yod Bet, Tet Vav, Yod Zain, Ma*",
			"Avigdor",
			"Azrikam",
			"Be'er Tuvia",
			"Beit Ezra",
			"Beit Guvrin",
			"Beit Nir",
			"Bitzaron",
			"Bnei Ayish",
			"Ein Tzurim",
			"Eitan",
			"Emunim",
			"Even Shmuel",
			"Ezer",
			"Galon",
			"Gan Yavne",
			"Gat",
			"Givati",
			"Hatzav",
			"Hatzor",
			"Kannot",
			"Kannot Industrial Zone",
			"Kedma",
			"Kfar Achim",
			"Kfar HaRif and Re'em Junction",
			"Kfar Menachem",
			"Kfar Warburg",
			"Kiryat Gat , Karmei Gat",
			"Kiryat Malachi",
			"Kommemiut",
			"Lakhish",
			"Masuot Itzhak",
			"Menucha",
			"Merkaz Shapira",
			"Nachla",
			"Negba",
			"Nehora",
			"Neveh Mivtach",
			"Nir Banim",
			"Nir Chen",
			"Noam",
			"Noga",
			"Orot",
			"Otzem",
			"Re'em Industrial Park",
			"Revacha",
			"Revadim",
			"Sdeh David",
			"Sdeh Moshe",
			"Sdeh Uziahu",
			"Sdeh Yoav",
			"Sgula",
			"Shachar",
			"Shafir",
			"Shalva",
			"Shtulim",
			"Talmei Yehiel",
			"Timorim",
			"Timorimg Industrial Zone",
			"Tlamim",
			"Uzza",
			"Vardon",
			"Yad Natan",
			"Yinon",
			"Zavdiel",
			"Zohar",
			"Zrahia",
			"Achihud",
			"Afek",
			"Afikim",
			"Alumot",
			"Arab al Na'im",
			"Arbel",
			"Arraba",
			"Ashdod Yacov Ichud",
			"Ashdot Yaakov Meuhad",
			"Atzmon (Segev)",
			"Avtalion",
			"Bar Lev Industrial Zone",
			"Beit Keshet",
			"Beit Rimon",
			"Beit Zera",
			"Bir al-Maksur",
			"Bu'eine Nujeidat",
			"Degania Alef",
			"Degania Bet",
			"Deir Hanna",
			"Dmeide",
			"Eilabun",
			"Eshbal",
			"Eshchar",
			"Ginosar",
			"Har Kamon - East",
			"Har Kamon - West",
			"Hararit Yachad",
			"Hazon",
			"HaZor'im",
			"Hodayot",
			"Hukok",
			"Hussniyya",
			"Ibillin",
			"Ilania",
			"Inbar",
			"Kabul",
			"Kadoorie",
			"Kalanit",
			"Kaukab Abu al-Hija",
			"Kfar Hanania",
			"Kfar Hittim",
			"Kfar Kama",
			"Kfar Manda",
			"Kfar Zeitim",
			"Kidmat Galil Industrial Zone",
			"Kinneret Academic College",
			"Koranit",
			"Kvutzat Kinneret",
			"Lavi",
			"Livnim",
			"Lotem and Hamdon",
			"Ma'aleh Zvia",
			"Maghar",
			"Manof",
			"Massad",
			"Migdal",
			"Misgav Regional Center",
			"Mitzpeh",
			"Mitzpeh Aviv",
			"Mitzpeh Netofa",
			"Moran",
			"Moreshet",
			"Moshavat Kinneret",
			"Ohalo and Beit Yerach",
			"Poria - Kfar Avoda",
			"Poria - Neve Oved",
			"Poria Illit",
			"Rakefet",
			"Ras al-ein",
			"Ravid",
			"Sakhnin",
			"Salama",
			"Sdeh Ilan",
			"Sha'ab",
			"Shadmot Dvora",
			"Sharona",
			"Shekhanya",
			"Shfaram",
			"Shorashim",
			"Tamra",
			"Tefahot",
			"Teradion Industrial Zone",
			"Tiberias",
			"Tzemach Industrial Zone",
			"Ya'ad",
			"Yasur",
			"Yavne'el",
			"Yodfat",
			"Yuvalim",
			"Alonei Itzhak",
			"Amikam",
			"Aviel",
			"Beit Hanania",
			"Binyamina",
			"Caesarea",
			"Caesarea Industrial Zone",
			"Caesarea Marine Center",
			"Dalia",
			"Ein HaEmek",
			"Ein HaShofet",
			"Ein Iron",
			"Ein Shemer",
			"Elyakim",
			"Gal'ed (Even Itzhak)",
			"Gan HaShomron",
			"Gan Shmuel",
			"Givat Ada",
			"Givat Haviva",
			"Givat Nili",
			"Givat Oz",
			"Hadera - Center",
			"Hadera - East",
			"Hadera - Neveh Haim",
			"Hadera - West",
			"HaZoreah and Yokneam Moshava",
			"Jisr az-Zarqa",
			"Karkur",
			"Kfar Glickson",
			"Kfar Pinnes",
			"Ma'agan Michael",
			"Ma'anit",
			"Ma'ayan Zvi",
			"Maor",
			"Megiddo",
			"Megiddo Prison",
			"Mevo Carmel Industrial Zone",
			"Midrach Oz",
			"Mishmar HaEmek",
			"Mishmarot",
			"Or Akiva",
			"Ort Binyamina",
			"Pardes Hanna",
			"Ramat HaNadiv",
			"Ramat HaShofet",
			"Ramot Menashe",
			"Regavim",
			"Regavim Industrial Zone",
			"Sdeh Itzhak",
			"Sdot Yam",
			"Sha'ar Menashe",
			"Talmei Elazar",
			"Yokneam Illit",
			"Yokneam Illit Industrial Zone",
			"Yokneam Moshava and HaZoreah",
			"Zichron Yacov",
			"Achita",
			"Adei Ad",
			"Alfei Menashe",
			"Amihai",
			"Ariel",
			"Atteret",
			"Avnei Hefetz",
			"Bar On Industrial Zone",
			"Barkan",
			"Beit Arie",
			"Beit El",
			"Beit Horon",
			"Brukhin",
			"Dolev",
			"Einav",
			"Elei Zahav",
			"Eli",
			"Elkana",
			"Elon Moreh",
			"Etz Ephraim",
			"Ganei Modi'in",
			"Geva Binyamin",
			"Halamish",
			"Har Bracha",
			"Hashmonaim",
			"Havat Yair",
			"Hermesh",
			"Hinanit",
			"Horasha",
			"Immanuel",
			"Itamar",
			"Itzhar",
			"Karnei Shomron",
			"Kdumim",
			"Kfar HaOranim",
			"Kfar Tapuach",
			"Kida",
			"Kiryat Netafim",
			"Kokhav HaShahar",
			"Kokhav Ya'akov",
			"Kokhav Ya'ir - Tzur Yigal",
			"Ma'aleh Levona",
			"Ma'aleh Michmash",
			"Ma'aleh Shomron",
			"Matityahu",
			"Megadlim",
			"Mevo Dotan",
			"Mevo Horon",
			"Migron",
			"Modi'in Illit",
			"Na'aleh",
			"Nachliel",
			"Nebi Samuel",
			"Neria",
			"Nili",
			"Nofei Nehemiah",
			"Nofim",
			"Ofarim",
			"Ofra",
			"Oranit",
			"Paduel",
			"Psagot",
			"Rechelim",
			"Reihan",
			"Revava",
			"Rimonim",
			"Salit",
			"Sha'ar Binyamin Industrial Zone",
			"Sha'arei Tikva",
			"Shaked",
			"Shavei Shomron",
			"Shilo",
			"Shvut Rachel",
			"Tal Menashe",
			"Talmon",
			"Tel Zion",
			"Tzofin",
			"Yakir",
			"גבעון החדשה",
			"Adanim",
			"Arsuf",
			"Batzra",
			"Beit Berl",
			"Beit Yehoshua",
			"Bnei Zion",
			"Elishema",
			"Even Yehuda",
			"Ga'ash",
			"Gan Haim",
			"Ganei Am",
			"Givat Hen",
			"Hagor",
			"Harutzim",
			"HaSharon Prison",
			"Herzeliya - Center and Glil Yam",
			"Herzeliya - Glil Yam and Center",
			"Herzeliya - Pituach",
			"Hod HaSharon",
			"Horashim",
			"Jaljulia",
			"Kafr Bara",
			"Kafr Misr",
			"Kfar Kassem",
			"Kfar Netter",
			"Kfar Saba",
			"Kfar Shmaryahu",
			"Matan",
			"Netanya - East",
			"Netanya - West",
			"Neveh Yamin",
			"Neveh Yarak",
			"Nir Eliyahu",
			"Nirit",
			"Ra'anana",
			"Ramat HaSharon",
			"Ramot HaShavim",
			"Rishpon",
			"Sdeh Warburg",
			"Sdei Hemed",
			"Shefayim",
			"Tel Itzhak",
			"Tzofit",
			"Udim",
			"Wingate Institute",
			"Yafhiv",
			"Yakum",
			"Yarkona",
			"Achiezer",
			"Ahisemech",
			"Ayanot",
			"Azaria",
			"Be'er Yacov",
			"Beit Dagan",
			"Beit Hanan",
			"Beit Hashmonai",
			"Beit Oved",
			"Beit Uziel",
			"Ben Shemen",
			"Ben Shemen Youth Village",
			"Gan Sorek",
			"Ganei Hadar",
			"Ganei Yochanan",
			"Ganot",
			"Ge'alya",
			"Gezer",
			"Gimzo",
			"Ginaton",
			"Hemed",
			"Hulda",
			"Irus",
			"Karmei Yossef",
			"Kfar Bilu",
			"Kfar Bin Nun",
			"Kfar Chabad",
			"Kfar Daniel",
			"Kfar HaNagid",
			"Kfar Rut",
			"Kfar Shmuel",
			"Lapid",
			"Lod",
			"Matzliach",
			"Mevo Modi'im",
			"Mishmar Ayalon",
			"Mishmar David",
			"Mishmar HaShiva",
			"Modi'in",
			"Modi'in - Ishpro Center",
			"Modi'in - Ligad Center",
			"Na'an",
			"Nesher Industrial Zone (Ramla)",
			"Ness Ziona",
			"Neta'im",
			"Netzer Sireni",
			"Nir Zvi",
			"Noff Ayalon",
			"Palmachim",
			"Palmachin Industrial Park",
			"Pdaya",
			"Ptachia",
			"Ramla",
			"Ramot Meir",
			"Rehovot",
			"Rishon LeZion - East",
			"Rishon LeZion - West",
			"Sha'alabim",
			"Shilat",
			"Sitria",
			"Tzafria",
			"Yad Rambam",
			"Yagel",
			"Yashresh",
			"Yatzitz",
			"Zeitan",
			"Zrifin Industrial Zone",
			"כרם בן שמן",
			"Abu Qrenat",
			"Abu Talul and the Bedouin Diaspora",
			"Arad",
			"Aroer (Ar'ara BaNegev)",
			"Ashalim",
			"Azuz",
			"Be'er Milka",
			"Ben Gurion College",
			"Bir Hadaj and the Bedouin Diaspora",
			"Darijat, Tel Arad and El Pura",
			"Dimona",
			"Dimona Industrial Zone",
			"Hura",
			"Kadesh Barneah",
			"Kmehin",
			"Kohla and Mikhol",
			"Kuseife and the Bedouin Diaspora",
			"Mashabei Sadeh",
			"Merhav Am",
			"Mikhol Kohla",
			"Mitzpeh Ramon",
			"Moladah, Al-Sayyid and the Bedouin diaspora",
			"Nafha Prison",
			"Nitzana",
			"Ovdat",
			"Qasr al-Sir and the Bedouin Diaspora",
			"Retamim",
			"Revivim",
			"Rotem Industrial Zone",
			"Sdeh Boker",
			"Segev Shalom and the Bedouin Diaspora",
			"Shanti BaMidbar",
			"Shoket Junction Center",
			"Tel Sheva",
			"Tlalim",
			"Umm Batin and the Bedouin Diaspora",
			"Wadi al-Na'am",
			"Yeruham",
			"אל-סייד",
			"Asseret",
			"Beit Elazari",
			"Beit Gamliel",
			"Beit Hilkia",
			"Ben Zakai",
			"Bnaya",
			"Bnei Darom",
			"Bnei Darom Compound",
			"Bnei Re'em",
			"Gan HaDarom",
			"Gan Shlomo",
			"Ganei Tal",
			"Gdera",
			"Gibton",
			"Givat Brenner",
			"Givat Washington",
			"Hafetz Haim",
			"Kerem BeYavne",
			"Kfar Aviv",
			"Kfar Mordechai",
			"Kidron",
			"Kiryat Ekron",
			"Kvutzat Yavne",
			"Maon Tzofia",
			"Mazkeret Batya",
			"Meishar",
			"Misgav Dov",
			"Netzer Hazani",
			"Nir Galim",
			"Shdema",
			"Yad Binyamin",
			"Yavne",
			"Yesodot",
			"Argaman",
			"Beka'ot",
			"Gilgal",
			"Gitit",
			"Hamra",
			"Hemdat",
			"Ma'aleh Ephraim",
			"Maskiot",
			"Masua",
			"Mehola",
			"Mekhora",
			"Mevuot Yericho",
			"Na'ama",
			"Netiv HaGdud",
			"Niran",
			"Petza'el",
			"Roee",
			"Rotem",
			"Shadmot Mechola",
			"Tomer",
			"Yafit",
			"Yitav",
			"Adi",
			"Afula",
			"Ahuzat Barak",
			"Alon HaGalil",
			"Alonei Abba",
			"Alonim",
			"Amen Settlements",
			"Balfuria",
			"Beit Shea'rim",
			"Beit Zaid",
			"Bethlehem of Galilee",
			"Daburiyya",
			"Dovrat",
			"Ed-Dahi",
			"Ein Dor",
			"Ein Harod",
			"Ein Mahil",
			"Gan Ner",
			"Gazit",
			"Genigar",
			"Geva",
			"Gidona",
			"Givat Ela",
			"Golani Memorial Site",
			"Gvat",
			"Hajajre",
			"Hanaton",
			"Harduf",
			"HaSollelim",
			"HaYogev",
			"Hever Settlements",
			"Hoshaya",
			"Ifat",
			"Iksal",
			"Ilut",
			"Ka'abiyye",
			"Ka'abiyye Tabbash",
			"Ka'abiyye-Tabbash-Hajajre",
			"Kafr Tabbash",
			"Kfar Baruch",
			"Kfar Gidon",
			"Kfar HaHoresh",
			"Kfar Kana",
			"Kfar Meissar",
			"Kfar Nehar HaYarden",
			"Kfar Tavor",
			"Kfar Yechezkel",
			"Kfar Yehoshua",
			"Magen Shaul",
			"Manshiya Zabda",
			"Mashhad",
			"Merhavia Kibbutz",
			"Merhavia Moshav",
			"Mevuot HaGilboa Industrial Zone",
			"Migdal HaEmek",
			"Mizra",
			"Muqeibla",
			"Nahalal",
			"Na'ura",
			"Nazareth",
			"Nazareth Illit",
			"Nin",
			"Nurit",
			"Ram On",
			"Ramat David",
			"Ramat Ishai",
			"Ramat Zvi",
			"Reineh",
			"Rumana",
			"Rumat al-Heib",
			"Sandala",
			"Sarid",
			"Sawad Humeria",
			"Sdeh Yacov",
			"Shibli",
			"Shimshit",
			"Shita and Gilboa Prison",
			"Sulam",
			"Taibe (Gilboa)",
			"Tamra (Gilboa)",
			"Tel Adashim",
			"Tel Yossef",
			"Timrat",
			"Turan",
			"Tzippori",
			"Umm al-Ghanam",
			"Uzeir",
			"Wadi Hamam",
			"Yael Settlements",
			"Yafia",
			"Yizre'el",
			"Zarzir",
			"אביטל",
			"אדירים",
			"ברק",
			"גדיש",
			"דבורה",
			"יעל",
			"מיטב",
			"מלאה",
			"מרכז אומן",
			"מרכז חבר",
			"ניר יפה",
			"עין חרוד איחוד",
			"פרזון",
			"Abu Snan",
			"Acco - Industrial Zone",
			"Acre",
			"Amiad",
			"Amirim",
			"Amka",
			"Amnon",
			"Amuka",
			"Ayelet HaShachar",
			"Bar Yochai",
			"Beit HaEmek",
			"Beit Jann",
			"Bi'ina",
			"Biriyeh",
			"Bustan HaGalil",
			"Carmiel Industrial Zone",
			"Deir al-Asad",
			"Ein al-Asad",
			"Ein HaMifratz",
			"Ein Kamonim",
			"Elifelet",
			"Farod",
			"Gadot",
			"Gilon Tzurit",
			"Gita",
			"Har Chalutz",
			"Harashim",
			"Hatzor HaGlilit",
			"Hatzor HaGlilit Industrial Zone",
			"Hulata",
			"Jadeidi-Makr",
			"Julis",
			"Kadarim",
			"Kadita",
			"Kahal",
			"Karkom",
			"Karmiel",
			"Kfar HaNassi",
			"Kfar Masaryk",
			"Kfar Shamai",
			"Kfar Yassif",
			"Kishor",
			"Kisra",
			"Klil",
			"Korazim Vered HaGalil",
			"Lapidot",
			"Lavon",
			"Lochamei HaGetaot",
			"Machanaim",
			"Machanaim landing pad",
			"Majd al-Krum",
			"Mazra'a",
			"Meron",
			"Migdal Tefen",
			"Mishmar HaYarden",
			"Nachaf",
			"Ness Amim",
			"Netiv HaShayara",
			"Or HaGanuz",
			"Oshrat",
			"Pelekh",
			"Rama",
			"Regba",
			"Rosh Pinna",
			"Safed",
			"Safsufa (Kfar Hoshen)",
			"Sajur",
			"Samia",
			"Sdeh Eliezer",
			"Shefer",
			"Sheikh Danun",
			"Shezor",
			"Shomrat",
			"Tal-El",
			"Tuba-Zangariyye",
			"Tuval",
			"Tzahar Industrial Zone",
			"Tzurit Gilon",
			"Yanuh-Jat",
			"Yarka",
			"Yesud Hama'ala",
			"כמאנה (סועאד)",
			"Al Arian",
			"Ar'ara",
			"Barkai",
			"Bart'a",
			"Basma",
			"bqa al-Gharbiyye",
			"Ein as-Sahla",
			"Harish",
			"Jatt",
			"Katzir",
			"Kfar Kara",
			"Lehavot Haviva",
			"Ma'aleh Iron",
			"Magal",
			"Mei Ami",
			"Meiser",
			"Metzer",
			"Mitzpeh Ilan",
			"Mu'awiya",
			"umm al-Fahm",
			"Umm al-Qutuf",
			"Ashkelon",
			"Ashkelon Northern Industrial Zone",
			"Ashkelon Southern Industrial Zone",
			"Bat Hadar",
			"Be'er Ganim",
			"Beit Shikma",
			"Berekhya",
			"Ge'a",
			"Heletz",
			"Hodaya",
			"Kfar Silver",
			"Kokhav Michael",
			"Mavki'im",
			"Mishan",
			"Nir Israel",
			"Nitzan",
			"Nitzanim",
			"Talmei Yaffe",
			"ניצן",
			"Beit HaGdi",
			"Bitha",
			"Bror Hayil",
			"Brosh",
			"Dorot",
			"Eshbol",
			"Eshel HaNassi",
			"Gilat",
			"Givolim Maagalim Melilot",
			"Gvulot",
			"Havat Shikmim",
			"Klachim",
			"Maagalim Givolim Melilot",
			"Mabu'im",
			"Maslul",
			"Melilot Givolim Maagalim",
			"Merhavim Educational Campus",
			"Netivot",
			"Nir Akiva",
			"Nir Moshe",
			"Ofakim",
			"Pa'amei Tashaz",
			"Patish",
			"Pduim",
			"Renan",
			"Rochama",
			"Sdeh Zvi",
			"Sharsheret",
			"Shavei Darom",
			"Shibolim",
			"Ta'ashur",
			"Talmei Bilu",
			"Tidhar",
			"Tifrach",
			"Urim",
			"Yoshivia",
			"Ze'elim",
			"Zru'a",
			"Afek and Lev Ha\"aretz Industrial Zone",
			"Bareket",
			"Be'erot Itzhak",
			"Beit Arif",
			"Beit Nechemia",
			"Bnei Atarot",
			"Einat",
			"Elad",
			"Gat Rimon",
			"Givat HaShlosha",
			"Giv'at Ko'ah",
			"Hadid",
			"Hatzav Industrial Zone",
			"Kfar Sirkin",
			"Kfar Truman",
			"Maas",
			"Magshimim",
			"Mazor",
			"Nachshonim",
			"Nechalim",
			"Nofech",
			"Petach Tikva",
			"Rinatya",
			"Rosh HaAyin",
			"Shoham",
			"Tirat Yehuda",
			"Beit Oren",
			"Daliyat al-Karmel",
			"Damon Priosn",
			"Givat Wolfson",
			"Isfiya",
			"Yearot HaCarmel"
	))),
	RU(new HashSet<>(Arrays.asList(
			"Беэр Ора",
			"Грофит",
			"Идан",
			"Ир Овот",
			"Йотвата",
			"Ктура",
			"Куши Рамон",
			"Лотан",
			"Неве Хариф",
			"Неот Смадар",
			"Паран",
			"Самар",
			"Сапир",
			"Хават Арнадель",
			"Хай-Бар Йотвата",
			"Хацева",
			"Цофар",
			"Цуким",
			"Шахрут",
			"Шитим",
			"Эйн Хацева",
			"Эйн Яхав",
			"Элифаз и Копи Тимны",
			"Яхель",
			"Абу-Гош",
			"Авиэзер",
			"Агур",
			"Адерет",
			"Аминадав",
			"Бар Гиора",
			"Бейт Зайт",
			"Бейт Меир",
			"Бейт Некофа",
			"Бейт Шемеш",
			"Бкоа",
			"Гефен",
			"Гиват Йешаягу",
			"Гиват Яарим",
			"Гивот Эден",
			"Гизо",
			"Заноах",
			"Зхария",
			"Иши",
			"Кирьят Анавим",
			"Кирьят Яарим",
			"Ксалон",
			"Кфар Зохарим",
			"Кфар Урия",
			"Латрун",
			"Лузит",
			"Маале ха-Хамиша",
			"Мата",
			"Махсия",
			"Мевасерет Цион",
			"Мево Бейтар",
			"Месилат Цион",
			"Моца Илит",
			"Натаф",
			"Нахам",
			"Нахшон",
			"Неве Илан",
			"Неве Михаэль (Рогалит)",
			"Неве Шалом",
			"Нес Харим",
			"Нетив ха-Ламед-Хей",
			"Нехуша",
			"Ора",
			"Промзона Брош",
			"Промзона Хар Тув - Цроа",
			"Рамат Разиэль",
			"Реторно - Гиват Шемеш",
			"Сдот Миха",
			"Сригим (Лион)",
			"Таль Шахар",
			"Таоз",
			"Таром",
			"Тирош",
			"Хар Адар",
			"Харэль",
			"Цальфон",
			"Цафририм",
			"Цроа",
			"Цуба",
			"Цур Хадасса",
			"Шоева",
			"Шореш",
			"Эвен Сапир",
			"Эйн Наккуба",
			"Эйн Рафа",
			"Эштаоль",
			"Яд ха-Шмона",
			"",
			"Аль Ариан",
			"Арара",
			"Бака аль Гарбия",
			"Баркай",
			"Барта",
			"Джатт",
			"Кацир",
			"Кфар Кара",
			"Лехавот Хавива",
			"Маале Ирон",
			"Магаль",
			"Мей Ами",
			"Мейсер",
			"Мецер",
			"Мицпе Илан",
			"Муавия",
			"Ум аль Кутуф",
			"Ум аль Фахм",
			"Хариш",
			"Эйн Ас-Сахла",
			"",
			"",
			"Абу Снан",
			"Айелет ха-Шахар",
			"Акко",
			"Акко - промзона",
			"Амиад",
			"Амирим",
			"Амка",
			"Амнон",
			"Амука",
			"Бар Йохай",
			"Бейт Джан",
			"Бейт ха-Эмек",
			"Биина",
			"Бирия",
			"Бустан ха-Галиль",
			"Гадот",
			"Гита",
			"Дждейда Макр",
			"Джулис",
			"Дир Эль-Асад",
			"Есуд ха-Маале",
			"Кадарим",
			"Кадита",
			"Карком",
			"Кармиэль",
			"Кахаль",
			"Кисра",
			"Кишор",
			"Клиль",
			"Коразим Веред ха-Галиль",
			"Кфар Масарик",
			"Кфар ха-Наси",
			"Кфар Шамай",
			"Кфар Ясиф",
			"Лавон",
			"Лапидот",
			"Лохамей ха-Гетаот",
			"Маджд Аль Крум",
			"Мазра",
			"Маханаим",
			"Маханаим посадочная площад",
			"Мерон",
			"Мигдаль Тефен",
			"Мишмар ха-Ярден",
			"Нахаф",
			"Нес Амос",
			"Нетив ха-Шаяра",
			"Ор ха-Гануз",
			"Ошрат",
			"Пелех",
			"Промзона Кармиэль",
			"Промзона Хацор ха-Глилит",
			"Промзона Цахар",
			"Рама",
			"Регба",
			"Рош Пина",
			"Саджур",
			"Самия",
			"Сафсуфа (кфар Хошен)",
			"Сдэ Элиэзер",
			"Таль-Эль",
			"Туба Зангария",
			"Туваль",
			"Фарод",
			"Харашим",
			"Хар-Халуц",
			"Хацор ха-Глилит",
			"Хулата",
			"Цурит Гилон",
			"Цфат",
			"Шезор",
			"Шейх Данун",
			"Шефер",
			"Шомрат",
			"Эйн аль Асад",
			"Эйн Камоним",
			"Эйн ха-Мифрац",
			"Элифелет",
			"Янух-Джат",
			"Ярка",
			"",
			"Авней Эйтан",
			"Алоней а-Башан",
			"Афик",
			"Бней Иеуда и Гиват Йоав",
			"Буката",
			"Гшур",
			"Йонатан",
			"Кешет",
			"Кфар Харув",
			"Маджд Аль Шамс",
			"Масаде",
			"Мево Хама",
			"Мером Голан",
			"Мецар",
			"Натур",
			"Неве Атив",
			"Неот Голан",
			"Нимрод",
			"Нов",
			"Одем",
			"Орталь",
			"Промзона Бней Йехуда",
			"Рамат Магшимим",
			"Хамад Гадер",
			"Хаспин",
			"Эйн Зиван",
			"Эйн Киния",
			"Эли Ад",
			"Эль Ром",
			"",
			"",
			"",
			"",
			"",
			"",
			"Авшалом",
			"Алумим",
			"Беэри",
			"Бней Нецарим",
			"Габим, колледж Сапир",
			"Гварам",
			"Декель",
			"Зиким",
			"Зимрат и Шува",
			"Йевуль",
			"Кармия",
			"Керем Шалом",
			"Кисуфим",
			"Кфар Аза",
			"Кфар Маймон и Тушия",
			"Маген",
			"Мефалсим",
			"Мивтахим Амиоз Йеша",
			"Наве",
			"Нахаль Оз",
			"Нетив ха-Асара",
			"Нир Ам",
			"Нир Ицхак",
			"Нир Оз",
			"Нирим",
			"Ор ха-Нер",
			"При Ган",
			"Реим",
			"Саад",
			"Сдерот, Ибим",
			"Сдэ Авраам",
			"Сдэ Ницан",
			"Суфа",
			"Тальмей Йосеф",
			"Тальмей Элиягу",
			"Тир Нир-Ам",
			"Ткума",
			"Ткума и Хават Израам",
			"Холит",
			"Цохар и Охад",
			"Шломит",
			"Шокеда",
			"Эйн ха-Бсор",
			"Эйн ха-Шлоша",
			"Эрез",
			"Яд Мордехай",
			"Ятед",
			"Яхини",
			"",
			"Бейт Альфа и Хефциба",
			"Бейт Йосеф",
			"Бейт ха-Шита",
			"Бейт Шеан",
			"Гешер",
			"Кфар Рупин",
			"Маале Гильбоа",
			"Маоз Хаим",
			"Менахемия",
			"Мерав",
			"Месилот",
			"Моледет",
			"Неве Ор",
			"Неве Эйтан",
			"Нир Давид",
			"Промзона Цваим",
			"Реабилитационный поселок М",
			"Ревая",
			"Рехов",
			"Решафим",
			"Сдей Трумот",
			"Сдэ Нахум",
			"Сдэ Элиягу",
			"Тель Теомим",
			"Тират Цви",
			"Хават Эден",
			"Хамадия",
			"Шлухот",
			"Щлафим",
			"Эйн ха-Нацив",
			"Ярдена",
			"Азор",
			"Бат-Ям",
			"Бней Брак",
			"Ганей Тиква",
			"Гиват Шмуэль",
			"Гиватаим",
			"Йехуд-Моноссон",
			"Кирьят Оно",
			"Микве Исраэль",
			"Ор Иеуда",
			"Рамат Ган - восток",
			"Рамат Ган - запад",
			"Савьон",
			"Тель Авив - Восток",
			"Тель Авив - Север После Ярко",
			"Тель Авив - Центральный рай",
			"Тель Авив - Южный Район и Яф",
			"Холон",
			"Ашкелон",
			"Бат Хадар",
			"Бейт Шикма",
			"Берекия",
			"Беэр Ганим",
			"Гея",
			"Кохав Михаэль",
			"Кфар Сильвер",
			"Мавкиим",
			"Мишан",
			"Нир Исраэль",
			"Ницан",
			"Ницан",
			"Ницарим",
			"Северная промзона Ашкелона",
			"Тальмей Яфа",
			"Хелец",
			"Ходайя",
			"Южная промзона Ашкелона",
			"",
			"",
			"Бейт ха-Гди",
			"Битха",
			"Брор Хайль",
			"Брош",
			"Гвулот",
			"Гилат",
			"Дорот",
			"Зруа",
			"Йошвия",
			"Клахим",
			"Маагалим Гиволим Мелитот",
			"Мабуим",
			"Маслуль",
			"Нетивот",
			"Нир Акива",
			"Нир Моше",
			"Офаким",
			"Паамей Ташаз",
			"Патиш",
			"Пдуим",
			"Ренан",
			"Рухама",
			"Сдэ Цви",
			"Таашур",
			"Тальмей Билу",
			"Тидхар",
			"Тифрах",
			"Урим",
			"Учебный центр Мерхавим",
			"Хават Шикмим",
			"Цеэлим",
			"Шавей Даром",
			"Шаршерет",
			"Шиболим",
			"Эшбол",
			"Эшель а-Наси",
			"",
			"Гиват Зеэв",
			"Иерусалим - Квартал Ораним",
			"Иерусалим - Промзона Атарот",
			"Иерусалим - Северный район",
			"Иерусалим - Южный квартал",
			"Иерусалим-Центральный, Зап",
			"Аргаман",
			"Бкаот",
			"Гильгаль",
			"Гитит",
			"Итав",
			"Маале Эфраим",
			"Маскиот",
			"Масуа",
			"Мевуот Йерихо",
			"Мехола",
			"Мехора",
			"Наама",
			"Нетив ха-Гдуд",
			"Ниран",
			"Пецаэль",
			"Рои",
			"Ротем",
			"Томер",
			"Хамра",
			"Хемдат",
			"Шадмот Мехола",
			"Яфит",
			"Адора",
			"Алон",
			"Алон Швут",
			"Альмон",
			"Амация",
			"Бат Аин",
			"Бейт Хагай",
			"Бейт Ятир",
			"Бейтар Илит",
			"Бней Дкалим",
			"Гваот",
			"Кармей Катиф",
			"Кармей Цур",
			"Кармель",
			"Кедар",
			"Кирьят Арба",
			"Кфар Адумим",
			"Кфар Эльдад",
			"Кфар Эцион",
			"Маале Адумим",
			"Маале Амос",
			"Маале Хевер",
			"Маон",
			"Мецад",
			"Мигдаль Оз",
			"Мицпе Йерихо",
			"Неве Даниэль",
			"Негохот",
			"Нета",
			"Нокдим",
			"Нофей Порат",
			"Отниэль",
			"Пней Кедем",
			"Промзона Мейтарим",
			"Рош Цурим",
			"Сансана",
			"Сусия",
			"Телем",
			"Тене Омарим",
			"Ткоа",
			"Хават Сде Бар",
			"Хар Амша",
			"Хар Гило",
			"Хеврон",
			"Шекеф",
			"Шени ле-Явне",
			"Шима",
			"Элиав",
			"Эльазар",
			"Эфрат",
			"Эшколот",
			"Альмагор",
			"Аниам",
			"Гиват Авни",
			"Канаф",
			"Кацрин",
			"Кацрин - Промзона",
			"Кедар",
			"Кидмат Цви",
			"Кфар Киш",
			"Мааган",
			"Маале Гамла",
			"Масада",
			"Рамот",
			"Тель Кацир",
			"Хад Нес",
			"Хаон",
			"Шааль",
			"Шаар ха-Голан",
			"Эйн Гев",
			"Аль Хавалед - запад",
			"Басмат Тивон",
			"Бет Альмин Тель Регев",
			"Ибтин",
			"Кирьят Ата",
			"Кирьят Бялик",
			"Кирьят Моцкин",
			"Кирьят Тивон",
			"Кирьят Ям",
			"Кфар Бялик",
			"Кфар Тиква",
			"Кфар ха-Маккаби",
			"Кфар Хасидим",
			"Кфар Хасидим",
			"Нофит",
			"Ораним",
			"Промзона Шаар Нааман",
			"Рамат Йоханан",
			"Рас Али",
			"Рехасим",
			"Уша",
			"Хавалед",
			"Шаар ха-Амаким",
			"Ягур",
			"Авигдор",
			"Азрикам",
			"Алума",
			"Аль Ази",
			"Аругот",
			"Ахва",
			"Ахузам",
			"Ашдод - алеф, бет, далет, хей",
			"Ашдод - гимел, вав, зайн",
			"Ашдод - йуд алеф, йуд бет, йу",
			"Ашдод - Северная промзона, П",
			"Ашдод - хет, тет, йод, йод гим",
			"Бейт Говрин",
			"Бейт Нир",
			"Бейт Эзра",
			"Беэр Тувья",
			"Бицарон",
			"Бней Аиш",
			"Вардон",
			"Галон",
			"Ган Явне",
			"Гат",
			"Гивати",
			"Завдиэль",
			"Зоар",
			"Зрахия",
			"Индустриальный парк Рам",
			"Инон",
			"Канот",
			"Кедма",
			"Кирьят Гат , Кармей Гат",
			"Кирьят Малахи",
			"Комемиют",
			"Кфар АРИФ и Цомет Раам",
			"Кфар Ахим",
			"Кфар Варбург",
			"Кфар Менахем",
			"Лахиш",
			"Масуот Ицхак",
			"Менуха",
			"Нахла",
			"Неве Мивтах",
			"Негба",
			"Неора",
			"Нир Баним",
			"Нир Хен",
			"Ноам",
			"Нога",
			"Орот",
			"Оцем",
			"Промзона Ад Халом",
			"Промзона Каннот",
			"Промзона Тиморим",
			"Ревадим",
			"Рехава",
			"Сгула",
			"Сде Давид",
			"Сдэ Йоав",
			"Сдэ Моше",
			"Сдэ Узиягу",
			"Тальмей Йехиэль",
			"Тиморим",
			"Тламим",
			"Уза",
			"Хацав",
			"Хацор",
			"Центр Шапира",
			"Шалва",
			"Шафир",
			"Шахар",
			"Штулим",
			"Эвен Шмуэль",
			"Эзер",
			"Эйн Цурим",
			"Эйтан",
			"Эмуним",
			"Яд Натан",
			"",
			"Абирим",
			"Авдон",
			"Авивим",
			"Алькош",
			"Альма",
			"Амир",
			"Араб Аль-Арамше",
			"Барам",
			"Бейт Хилель",
			"Бен Ами",
			"Бецет",
			"Гаатон",
			"Гешер ха-Зив",
			"Гонен",
			"Горен",
			"Горнот ха-Галиль",
			"Дальтон",
			"Дан",
			"Дафна",
			"Джиш (Гуш Халав)",
			"Дишон",
			"Довев",
			"Зарит",
			"Идмит",
			"Ирон",
			"Ифтах",
			"Йехиам",
			"Кабри",
			"Керем Бен Зимра",
			"Кирьят Шмона",
			"Кфар Блум",
			"Кфар Врадим",
			"Кфар Гилади",
			"Кфар Сольд",
			"Лехавот ха-Башан",
			"Лехман",
			"Маалот Таршиха",
			"Мааян Барух",
			"Малкия",
			"Манара",
			"Манот",
			"Маона",
			"Маргалиот",
			"Матат",
			"Метула",
			"Мецуба",
			"Миилия",
			"Мисгав Ам",
			"Нагария",
			"Неве Зив",
			"Неот Мордехай",
			"Нетуа",
			"Пекиин",
			"Промзона Ахзив Милуот",
			"Промзона Рамат Дальтон",
			"Раджар",
			"Рамот Нафтали",
			"Рехания",
			"Рош ха-Никра",
			"Саар",
			"Саса",
			"Сдэ Нехемия",
			"Снир",
			"Тель Хай",
			"Фассута",
			"ха-Гошрим",
			"Ханита",
			"Хила",
			"Хосен",
			"Хурфеш",
			"Цивон",
			"Цуриэль",
			"Шаар Йешув",
			"Шавей Цион",
			"Шамир",
			"Школа Сде Мирон",
			"Шломи",
			"Шомера",
			"Штула",
			"Эвен Менахем",
			"Эврон",
			"Эйлон",
			"Эйн Яаков",
			"Юваль",
			"Яара",
			"",
			"Авиэль",
			"Алоней Ицхак",
			"Амикам",
			"Бейт Ханания",
			"Биньямина",
			"Галед (Эвен Ицхак)",
			"Ган ха-Шомрон",
			"Ган Шмуэль",
			"Гиват Ада",
			"Гиват Нили",
			"Гиват Оз",
			"Гиват Хавива",
			"Далья",
			"Джиср аз-Зарка",
			"Зихрон Яаков",
			"Йокнеам Илит",
			"Йокнеам ха-Мошава и ха-Зоре",
			"Каркур",
			"Кейсария",
			"Кфар Гликсон",
			"Кфар Пинес",
			"Мааган Михаэль",
			"Маанит",
			"Мааян Цви",
			"Маор",
			"Мегиддо",
			"Мидрах Оз",
			"Мишмар ха-Эмек",
			"Мишмарот",
			"Морской центр Кейсария",
			"Ор Акива",
			"Орт Биньямина",
			"Пардес Хана",
			"Промзона Йокнеам Илит",
			"Промзона Кейсария",
			"Промзона Мево Кармель",
			"Промзона Регавим",
			"Рамат ха-Надив",
			"Рамат ха-Шофет",
			"Рамот Менаше",
			"Регавим",
			"Сдот Ям",
			"Сдэ Ицхак",
			"Тальмей Элиэзер",
			"Тюрма Магидо",
			"Хадера - восток",
			"Хадера - запад",
			"Хадера - Неве Хаим",
			"Хадера - центр",
			"Шаар Менаше",
			"Эйн Ирон",
			"Эйн ха-Шофет",
			"Эйн ха-Эмек",
			"Эйн Шемер",
			"Эльяким",
			"Авнат",
			"Альмог",
			"Бейт ха-Арава",
			"Веред Йерихо",
			"Гостиницы Мертвого Моря",
			"Калия",
			"Массада",
			"Мецокей Драгот",
			"Мицпе Шалем",
			"Неве Зохар",
			"Неот ха-Кикар",
			"Отели Мертого моря - Центра",
			"Эйн Бокек",
			"Эйн Геди",
			"Эйн Геди спа",
			"Эйн Тамар",
			"",
			"Авталион",
			"Академический колледж Кине",
			"Алумот",
			"Араб эль-Наим",
			"Араба",
			"Арбель",
			"Афек",
			"Афиким",
			"Ахихуд",
			"Ацмон (Сегев)",
			"Ашдот Яаков Ихуд",
			"Ашдот Яаков Меухад",
			"Бейт Зера",
			"Бейт Кешет",
			"Бейт Римон",
			"Бир аль-Максур",
			"Буэйне-Нуджейдат",
			"Гиносар",
			"Дгания Алеф",
			"Дгания Бет",
			"Дир Хана",
			"Дмейде",
			"Иблин",
			"Илания",
			"Инбар",
			"Йодфат",
			"Кабул",
			"Кадури",
			"Каланит",
			"Каукаб Абу Альхижда",
			"Квуцат Кинерет",
			"Кинерет ха-Мошава",
			"Коранит",
			"Кфар Зеитим",
			"Кфар Кама",
			"Кфар Манда",
			"Кфар Ханания",
			"Кфар Хитим",
			"Лави",
			"Ливним",
			"Лотем и Хамдон",
			"Маале Цвия",
			"Маноф",
			"Массад",
			"Мигдаль",
			"Мицпе",
			"Мицпе Авив",
			"Мицпе Нетофа",
			"Моран",
			"Морешет",
			"Охало и Бейт Йерах",
			"Пория Илит",
			"Пория Кфар Авода",
			"Пория Неве Овед",
			"Промзона Бар-Лев",
			"Промзона Кидмат Галиль",
			"Промзона Терадион",
			"Промзона Цемах",
			"Равид",
			"Районный центр Мисгав",
			"Ракефет",
			"Рас аль-Эйн",
			"Салама",
			"Сахнин",
			"Сдэ Илан",
			"Тамра",
			"Тверия",
			"Тфахот",
			"Хазон",
			"ха-Зорим",
			"Хар Камон - Восток",
			"Хар Камон - Запад",
			"Харарит Яхад",
			"Ходайот",
			"Хукок",
			"Хусния",
			"Шааб",
			"Шадмот Двора",
			"Шарона",
			"Шехания",
			"Шорашим",
			"Шфарам",
			"Эйлабун",
			"Эшбаль",
			"Эшхар",
			"Ювалим",
			"Яад",
			"Явниэль",
			"Ясур",
			"",
			"Авней Хефец",
			"Адей Ад",
			"Алей Захав",
			"Алон ха-Море",
			"Алфей Менаше",
			"Амихай",
			"Ариэль",
			"Атерет",
			"Ахия",
			"Баркан",
			"Бейт Арье",
			"Бейт Хорон",
			"Бейт Эль",
			"Брухин",
			"Ганей Модиин",
			"Гева Биньямин",
			"Долев",
			"Имануель",
			"Итамар",
			"Ицхар",
			"Карней Шомрон",
			"Кдумим",
			"Кида",
			"Кирьят Нетафим",
			"Кохав ха-Шахар",
			"Кохав Яаков",
			"Кохав Яир - Цур Игаль",
			"Кфар Тапуах",
			"Кфар ха-Ораним",
			"Маале Левона",
			"Маале Михмаш",
			"Маале Шомрон",
			"Матитьягу",
			"Мево Дотан",
			"Мево Хорон",
			"Мегадлим",
			"Мигрон",
			"Модиин Илит",
			"Наале",
			"Нахлиэль",
			"Неби Самуэль",
			"Нерия",
			"Нили",
			"Нофей Нехемия",
			"Нофим",
			"Оранит",
			"Офарим",
			"Офра",
			"Падуель",
			"Промзона Бар Он",
			"Промзона Шаар Биньямин",
			"Псагот",
			"Ревава",
			"Рейхан",
			"Рехелим",
			"Римоним",
			"Салит",
			"Тальмон",
			"Тель Менаше",
			"Тель Цион",
			"Хават Яир",
			"Халамиш",
			"Хар Браха",
			"Хашмонаим",
			"Хермеш",
			"Хинанит",
			"Хораша",
			"Цофин",
			"Шаарей Тиква",
			"Шавей Шомрон",
			"Шакед",
			"Швут Рахель",
			"Шило",
			"Эйнав",
			"Эли",
			"Элькана",
			"Эц Эфраим",
			"Якир",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"Ади",
			"Алон а-Галиль",
			"Алоней Аба",
			"Алоним",
			"Афула",
			"Ахузат Барак",
			"Бальфурия",
			"Бейт Зайд",
			"Бейт Лехем ха-Глилит",
			"Бейт Шеарим",
			"Вади Эль Хамам",
			"Газит",
			"Ган Нер",
			"Гват",
			"Гева",
			"Генигар",
			"Гиват Эла",
			"Гидона",
			"Дабурия",
			"Дахи",
			"Доврат",
			"Зарзир",
			"Изреэль",
			"Иксаль",
			"Илут",
			"Ифат",
			"Каабия",
			"Каабия Табаш",
			"Кфар Барух",
			"Кфар Гидон",
			"Кфар Иешуа",
			"Кфар Ихезкиель",
			"Кфар Кана",
			"Кфар Мейсар",
			"Кфар Нехар ха-Ярден",
			"Кфар Табаш",
			"Кфар Тавор",
			"Кфар ха-Хореш",
			"Маген Шауль",
			"Маншия Забда",
			"Машхад",
			"Мемориал Голани",
			"Мерхавия Киббуц",
			"Мерхавия Мошав",
			"Мигдаль ха-Эмек",
			"Мизра",
			"Мукейбла",
			"Наура",
			"Нахалаль",
			"Нацерет",
			"Нацерет Илит",
			"Нин",
			"Нурит",
			"Поселения Амен",
			"Поселения Хевер",
			"Поселения Яэль",
			"Промзона Мевуот ха-Гильбоа",
			"Райне",
			"Рам Он",
			"Рамат Давид",
			"Рамат Ишай",
			"Рамат Цви",
			"Румана",
			"Румат эль-Хейб",
			"Сандала",
			"Сарид",
			"Сауад Хумейра",
			"Сдэ Яаков",
			"Сулам",
			"Тайбе (Гильбоа)",
			"Тамра (Гильбоа)",
			"Тель Адашим",
			"Тель Йосеф",
			"Тимрат",
			"Туран",
			"Тюрьма Шита и Гильбоа",
			"Узиер",
			"Ум аль Ганам",
			"Хаджаджаре",
			"ха-Йогев",
			"Ханатон",
			"Хардуф",
			"ха-Солелим",
			"Хошайя",
			"Ципори",
			"Шибли",
			"Шимшит",
			"Эйн Дор",
			"Эйн Махель",
			"Эйн Харод",
			"Яфиа",
			"ישובי אמן",
			"ישובי חבר",
			"ישובי יעל",
			"Кфар Галим",
			"Нешер",
			"Тират Кармель",
			"Хаифа - Краёт и Мифрац",
			"Хайфа - запад",
			"Хайфа - Кармел и Нижний горо",
			"Хайфа - Неве Шаанан и Рамот",
			"ха-Хотрим",
			"",
			"Авихайль",
			"Азриэль",
			"Академический центр Рупин",
			"Амац",
			"Ахитув",
			"Бат Хен",
			"Бат Хефер",
			"Бахан",
			"Бейт Аарон",
			"Бейт Ицхак - Щаар Хефер",
			"Бейт Хазон",
			"Бейт ха-Леви",
			"Бейт Херут",
			"Бейт Яннай",
			"Беэротаим",
			"Бней Дрор",
			"Бургата",
			"Ган Йошиа",
			"Геулей Тейман",
			"Геулим",
			"Гиват Хаим Меухад",
			"Гиват Хаим Эхуд",
			"Гиват Шапира",
			"Гинот Хадар",
			"Земер",
			"Кадима",
			"Калансуа",
			"Кфар Авода",
			"Кфар Виткин",
			"Кфар Йона",
			"Кфар Мона",
			"Кфар Хаим",
			"Кфар ха-Роэ",
			"Кфар Хес",
			"Кфар Явец",
			"Кфар Ядидья",
			"Мааборот",
			"Михморет",
			"Мишмар ха-Шарон",
			"Мишмерет",
			"Неурим",
			"Ницаней Оз",
			"Нордия",
			"Олеш",
			"Пардесия",
			"Порат",
			"Промзона Тира",
			"Промзона Эмек Хефер",
			"Рамат ха-Ковеш",
			"Тайбе",
			"Тель Монд",
			"Тира",
			"Тнувот",
			"Хавацелет а-Шарон и Цукей Я",
			"Хадар Ам",
			"ха-Маапиль",
			"Ханиэль",
			"ха-Оген",
			"Херев Леат",
			"Херут",
			"Хибат Цион",
			"Хогла",
			"Хофит",
			"Цоран",
			"Цур Ицхак",
			"Цур Моше",
			"Цур Натан",
			"Шаар Эфраим",
			"Шошанат ха-Амаким",
			"Эйн Веред",
			"Эйн Сарид",
			"Эйн ха-Хореш",
			"Эльяхин",
			"Эльяшив",
			"Эяль",
			"Яаф",
			"Яд Хана",
			"Янув",
			"Атлит",
			"Бат Шломо",
			"Бейт Цви",
			"Гева Кармель",
			"Дор",
			"Керем Махарал",
			"Мегадим",
			"Меир Шфея",
			"Молодежный поселок Кфар Ор",
			"Нахшолим",
			"Неве Ям",
			"Нир Эцион",
			"Офер",
			"Промзона Нир Эцион",
			"Фурадис",
			"ха-Боним",
			"Центр Мерав",
			"Цруфа",
			"Эйн Аяла",
			"Эйн Кармель",
			"Эйн Од",
			"Эйн Ход",
			"Бейт Кама",
			"Беэр Шева - восток",
			"Беэр Шева - запад",
			"Беэр Шева - север",
			"Беэр шева - Южная часть",
			"Гивот Бар",
			"Двир",
			"Кармит",
			"Крамим",
			"Лакия и диаспора",
			"Лахав",
			"Лехавим",
			"Мейтар",
			"Мишмар ха-Негев",
			"Наот Ховав",
			"Неватим",
			"Омер",
			"Промзона Идан ха-Негев",
			"Рахат и диаспора",
			"Тирабин аль-Сана и диаспора",
			"Хацерим",
			"Шоваль",
			"Шомрия",
			"",
			"Аданим",
			"Арсуф",
			"Бацра",
			"Бейт Берл",
			"Бейт Иешуа",
			"Бней Цион",
			"Гааш",
			"Ган Хаим",
			"Ганей Ам",
			"Герцлия - Питуах",
			"Герцлия - центр и Глиль Ям",
			"Гиват Хен",
			"Джальджулия",
			"Институт Вингейт",
			"Кфар Бара",
			"Кфар Касем",
			"Кфар Малаль",
			"Кфар Неттер",
			"Кфар Саба",
			"Кфар Шмариягу",
			"Матан",
			"Неве Ямин",
			"Неве Ярак",
			"Нетания - восток",
			"Нетания - запад",
			"Нир Элиягу",
			"Нирит",
			"Раанана",
			"Рамат ха-Шарон",
			"Рамот ха-Шавим",
			"Ришпон",
			"Сдей Хемед",
			"Сдэ Варбург",
			"Тель Ицхак",
			"Тюрма а- Шарон",
			"Удим",
			"Хагор",
			"Харуцим",
			"Ход ха-Шарон",
			"Хорашим",
			"Цофит",
			"Шфаим",
			"Эвен Иеуда",
			"Элишема",
			"Якум",
			"Яркона",
			"Ярхив",
			"",
			"Азария",
			"Ахисемех",
			"Ахиэзер",
			"Аянот",
			"Бейт Даган",
			"Бейт Овед",
			"Бейт Узиэль",
			"Бейт Ханан",
			"Бейт Хашмонаи",
			"Бен Шемен",
			"Беэр Яаков",
			"Ган Шорек",
			"Ганей Йоханан",
			"Ганей Хадар",
			"Ганот",
			"Геалия",
			"Гезер",
			"Гимзо",
			"Гинатон",
			"Зейтан",
			"индустриальный парк Пальма",
			"Ирус",
			"Кармей Йосеф",
			"Кфар Билу",
			"Кфар Бин Нун",
			"Кфар Даниэль",
			"Кфар Ноар Бен Шемен",
			"Кфар Рут",
			"Кфар Хабад",
			"Кфар ха-Нагид",
			"Кфар Шмуэль",
			"Лапид",
			"Лод",
			"Мацлиах",
			"Мево Модиим",
			"Мишмар Аялон",
			"Мишмар Давид",
			"Мишмар ха-Шива",
			"Модиин",
			"Модиин - Ишпро центр",
			"Модиин - центр Лигад",
			"Наан",
			"Нес Циона",
			"Нетаим",
			"Нецер Сирени",
			"Нир Цви",
			"Ноф Аялон",
			"Пальмахим",
			"Пдая",
			"Промзона Нешер (Рамла)",
			"Промзона Црифин",
			"Птахия",
			"Рамла",
			"Рамот Меир",
			"Реховот",
			"Ришон Ле Цион - Восток",
			"Ришон ле Цион - запад",
			"Ситрия",
			"Хемед",
			"Хульда",
			"Цафрия",
			"Шаалабим",
			"Шилат",
			"Ягель",
			"Яд Рамбам",
			"Яциц",
			"Яшреш",
			"Промзона Шхорет",
			"Эйлат",
			"Эйлот",
			"Асерет",
			"Бейт Гамлиэль",
			"Бейт Хилькия",
			"Бейт Эльазари",
			"Бен Закай",
			"Бнайя",
			"Бней Даром",
			"Бней Рам",
			"Гадера",
			"Ган ха-Даром",
			"Ган Шломо",
			"Ганей Таль",
			"Гибтон",
			"Гиват Бренер",
			"Гиват Вашингтон",
			"Есодот",
			"Квуцат Явне",
			"Керем БеЯвне",
			"Кидрон",
			"Кирьят Экрон",
			"Кфар Авив",
			"Кфар Мордехай",
			"Мазкерет Батья",
			"Маон Цофия",
			"Мейшар",
			"Мисгав Дов",
			"Нецер Хазани",
			"Нир Галим",
			"Участок Бней Дрор",
			"Хефец Хаим",
			"Шдема",
			"Явне",
			"Яд Биньямин",
			"",
			"",
			"Абу Кренат",
			"Абу Талуль и диаспора",
			"Азуз",
			"Арад",
			"Ароер (Арара ба Негев)",
			"Ашалим",
			"Беэр Милка",
			"Бир Хададж и диаспора",
			"Вади аль-Наам",
			"Димона",
			"Дриджат, Тель Арад, Аль Фура",
			"Йерухам",
			"Кадеш Барнеа",
			"Каср аль-Сир и диаспора",
			"Кмеин",
			"Колледж Бен Гурион",
			"Кусфия и диаспора",
			"Кухле, Макхул",
			"Машавей Саде",
			"Мерхав Ам",
			"Мицпе Рамон",
			"Молада, Эль-Саид и диаспора",
			"Ницана",
			"Овдат",
			"Промзона Димона",
			"Промзона Ротем",
			"Ревивим",
			"Ретамим",
			"Сдэ Бокер",
			"Сегев Шалом и диаспора",
			"Тель Шева",
			"Тлалим",
			"Тюрма Нефха",
			"Ум Батин и диаспора",
			"Хура",
			"Центр Перекресток Шокет",
			"Шанти ба Мидбар",
			"Бейт Орен",
			"Гиват Вольфсон",
			"Далият эль Кармель",
			"Исфия",
			"Тюрьма Дамон",
			"Яарот ха-Кармель",
			"Барекет",
			"Беит Нехемия",
			"Бейт Ариф",
			"Беэрот Ицхак",
			"Бней Атарот",
			"Гат Римон",
			"Гиват Коах",
			"Гиват ха-Шлоша",
			"Кфар Сиркин",
			"Кфар Труман",
			"Мааш",
			"Магшимим",
			"Мазор",
			"Нахшоним",
			"Нехалим",
			"Нофех",
			"Петах Тиква",
			"Промзона Афек и Лев ха-Арец",
			"Промзона Хацав",
			"Ринатия",
			"Рош ха-Айн",
			"Тират Иеуда",
			"Хадид",
			"Шохам",
			"Эйнат",
			"Эльад"
	))),
	AR(new HashSet<>(Arrays.asList(
			"بيت أورن",
			"جفعات فولفسون",
			"دالية الكرمل",
			"سجن الدامون",
			"عسفيا",
			"غابات الكرمل",
			"ألموغ",
			"ايفنات",
			"بيت هعاربا",
			"حمامات عين جدي",
			"عين بوكك",
			"عين تمار",
			"عين جدي",
			"فنادق البحر الميت",
			"فنادق البحر الميت",
			"فيرد يريحو",
			"كلياه",
			"متساده",
			"متسبي شلم",
			"متسوكي دراجوت",
			"نؤوت هكيكار",
			"نافيه زوهر",
			"أحيهود",
			"أرابل",
			"إشبال",
			"إشحار",
			"أشدوت يعقوب إيحود",
			"أشدوت يعقوب مئوحاد",
			"إعبلين",
			"أفيك",
			"أفيكيم",
			"ألوموت",
			"افتليون",
			"البعنة النجيدات",
			"الحصينية",
			"الكلية الأكاديمية كنيرت",
			"المركز الاقليمي مسجاف",
			"المغار",
			"المنطقة الصناعية بار- ليف",
			"المنطقة الصناعية ترديون",
			"المنطقة الصناعية تسيمح",
			"المنطقة الصناعية كيدمات جل",
			"اوهلو وبيت يريح",
			"ايلانيا",
			"بئر المكسور",
			"بوريا عيليت",
			"بوريا كفار عفوداه",
			"بوريا نافيه عوفيد",
			"بيت ريمون",
			"بيت زيرع",
			"بيت كيشت",
			"تفحوت",
			"جينوسار",
			"حزون",
			"حوكوك",
			"دجانيا أ‘",
			"دجانيا ب‘",
			"دير حنا",
			"راس العين",
			"ربيد",
			"ركيفت",
			"سارونا",
			"سخنين",
			"سديه إيلان",
			"سلامه",
			"شخانيا",
			"شدموت دفوراه",
			"شعب",
			"شفاعمرو",
			"شورشيم",
			"ضميده",
			"طبريا",
			"طبريا مجموعة",
			"طبريا موشفا",
			"طمره",
			"عتسمون (سيجف)",
			"عرابه",
			"عرب النعيم",
			"عيلبون",
			"عينبار",
			"كابول",
			"كادوري",
			"كفار حيطيم",
			"كفار زيتيم",
			"كفر حنانيا",
			"كفر كما",
			"كفر مندا",
			"كلانيت",
			"كورنيت",
			"كوكب ابو الهيجا",
			"لبنيم",
			"لفي",
			"لوطم وحمدون",
			"مانوف",
			"متسبي",
			"متسبي أفيف",
			"متسبي نتوفا",
			"مجدال",
			"مساد",
			"معليه تسفيا",
			"موران",
			"موريشت",
			"هار كمون- شرق",
			"هار كمون- غرب",
			"هرريت-ياحد",
			"هزورعيم",
			"هوديوت",
			"ياعد",
			"يسعور",
			"يفنال",
			"يودفت",
			"يوفاليم",
			"",
			"",
			"إليفلت",
			"أمنون",
			"أميريم",
			"أور هغنوز",
			"أوشرات",
			"أييلت هشاحر",
			"ابو سنان",
			"البعنة",
			"الرامه",
			"الشيخ دنون",
			"المنطقة الصناعية تساحار",
			"المنطقة الصناعية حتسور هجل",
			"المنطقة الصناعية كرميئيل",
			"بار يوحاي",
			"بستان الجليل",
			"بيت جن",
			"بيت هعيمك",
			"بيريه",
			"بيلخ",
			"تال- إيل",
			"تسوريت، جيلون",
			"توفال",
			"جادوت",
			"جديدة المكر",
			"جولس",
			"جيته",
			"حتسور هجليليت",
			"حوراشيم",
			"حولاتا",
			"خليل",
			"خورزيم، ورد هجليل",
			"دير الأسد",
			"رجبة",
			"روش بينا",
			"ساجور",
			"سديه اليعيزر",
			"سميع",
			"شازور",
			"شومرات",
			"شيفر",
			"صفد",
			"صفصوفة - كفار حوشن",
			"طوبا الزنغرية",
			"عكا",
			"عكا- المنطقة الصناعية",
			"عمكاه",
			"عموكاه",
			"عميعاد",
			"عين الأسد",
			"عين كمونيم",
			"عين همفراتس",
			"فرود",
			"كاحال",
			"كداريم",
			"كديتا",
			"كركوم",
			"كرمئيل",
			"كسرى",
			"كفار شماي",
			"كفار مسريك",
			"كفار هنسي",
			"كفر ياسيف",
			"كيشور",
			"لفون",
			"لفيدوت",
			"لوحمي هجيتؤوت",
			"مجد الكروم",
			"مجدال تيفن",
			"محانييم",
			"مزرعة",
			"مشمار هيردن",
			"مهبط محانايم",
			"ميرون",
			"نتيف هشيرا",
			"نحف",
			"نس عاميم",
			"هار- حلوتس",
			"يانوح - جت",
			"يركا",
			"يسود همعلاه",
			"",
			"أفني ايتان",
			"أفيك",
			"ألوني هبشان",
			"إلي عاد",
			"أورطال",
			"الروم",
			"المنطقة الصناعية بني يهودا",
			"اودم",
			"بقعاثا",
			"بني يهودا وجفعات يوئاف",
			"جاشور",
			"حاسفين",
			"حامات جادير",
			"رمات مجشيميم",
			"عين زيفان",
			"عين قينيا",
			"كفر حروب",
			"كيشت",
			"مافو حاماه",
			"مجدل شمس",
			"مروم جولان",
			"مسعده",
			"ميتسار",
			"نؤوت جولان",
			"ناطور",
			"نافيه أطيب",
			"نمرود",
			"نوف",
			"يونتان",
			"",
			"أحيسيمخ",
			"أحيعزر",
			"الرملة-",
			"اللد",
			"المنطقة الصناعية نيشر (الرم",
			"ايروس",
			"بئير يعقوب",
			"باديا",
			"بلمحيم",
			"بن شيمن",
			"بيت حشمونائي",
			"بيت حنان",
			"بيت دجان",
			"بيت عوزيئيل",
			"بيت عوفيد",
			"تسفاريه",
			"تعسيون تسريفين",
			"جالية",
			"جان شورك",
			"جانوت",
			"جاني هدار",
			"جاني يوحانان",
			"جمزو",
			"جيزر",
			"جينتون",
			"حولداه",
			"حيمد",
			"راموت مئير",
			"رحوفوت",
			"ريشون لتسيون - شرق",
			"ريشون لتسيون - غرب",
			"زيتان",
			"ستاريه",
			"شعلبيم",
			"شيلات",
			"عازاريه",
			"عينوت",
			"فتحية",
			"كرمي يوسف",
			"كفار بن نون",
			"كفار بيلو",
			"كفار حاباد",
			"كفار دانيئل",
			"كفار روت",
			"كفار شموئيل",
			"كفار هنجيد",
			"كفر نوعر بن شيمن",
			"لبيد",
			"مافو موديعيم",
			"متسليح",
			"متنزه تعسيوت بلماحيم",
			"مشمار أيلون",
			"مشمار دافيد",
			"مشمار هشبفعاه",
			"موديعين",
			"موديعين- ليجد سنتر",
			"موديعين- يشفرو سنتر",
			"ناعن",
			"نتاعيم",
			"نس تسيونا",
			"نوف أيالون",
			"نيتسر سراني",
			"نير تسفي",
			"يتسيس",
			"يد رمبام",
			"يشرش",
			"ييجال",
			"أرجمان",
			"بتسئيل",
			"بكعوت",
			"تومر",
			"جلجل",
			"جيتيت",
			"حمدات",
			"حمرا",
			"روتم",
			"روعي",
			"شدموت محولا",
			"محوله",
			"مخوراه",
			"مسوأه",
			"مشخيوت",
			"معليه افرايم",
			"مفوؤت يريحو",
			"نتيف هجدود",
			"نعران",
			"نعماه",
			"يافيت",
			"ييطاب",
			"",
			"القدس - المقطع الجنوبي",
			"القدس - المقطع الشرقي, لمقطع",
			"القدس - المنطقة الصناعية عط",
			"القدس - مقطع اورانيم",
			"القدس- شمال وألونيم",
			"جفعات زئيف",
			"أييلت",
			"المنطقة الصناعية شحوروت",
			"ايالوت",
			"أورة",
			"ابو غوش",
			"ادرت",
			"اشتوئيل",
			"افيعزير",
			"المنطقة الصناعية - تسارعا",
			"المنطقة الصناعية بروش",
			"ايفين سفير",
			"بار جيورا",
			"بكوع",
			"بيت زيت",
			"بيت شيمش",
			"بيت مئير",
			"بيت نقوبا",
			"تاعوز",
			"تال شاحار",
			"تروم",
			"تسافريريم",
			"تسلفون",
			"تسور هداسا",
			"تسوفا",
			"تيروش",
			"جفاعوت عيدن",
			"جفعات يشعياهو",
			"جفعات يعاريم",
			"جفن",
			"جيزو",
			"رطورنو- جفعات شيمش",
			"رمات رازئيل",
			"زكريا",
			"زنوح",
			"سدوت ميخا",
			"شريجيم (ليؤون)",
			"شوأفا",
			"شورش",
			"صرعه",
			"عاجور",
			"عمينداف",
			"عين رافا",
			"عين نقوبا",
			"كريات عنابيم",
			"كريات يعاريم",
			"كسلون",
			"كفار أوريا",
			"كفار زوهريم",
			"لطرون",
			"لوزيت",
			"مافو بيتار",
			"مبريشت تسيون",
			"محسيه",
			"مسيلوت تسيون",
			"مطاع",
			"معليه هحميشا",
			"موتسا عيليت",
			"نافيه إيلان",
			"نافيه شالوم",
			"نافيه مبيخائيل (روجليت)",
			"نتيف هيلا",
			"نحشون",
			"نحوشا",
			"نس هاريم",
			"نطاف",
			"نوحم",
			"هار آدار",
			"هرئيل",
			"يد هشمونه",
			"يشعي",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"Amen Settlements I Tavor Area",
			"Hever Settlements I Tavor Area",
			"Yael Settlements I Tavor Area",
			"أحوزات براك",
			"ألون هجليل",
			"ألوني أبا",
			"ألونيم",
			"اكسال",
			"الدحي",
			"الرينه",
			"الطيبه (جلبوع)",
			"العزير",
			"العفولة-",
			"المشهد",
			"المنطقة الصناعية مبؤوت هجل",
			"الناصرة",
			"الناصرة العليا",
			"الناعورة",
			"ام الغنم",
			"بلدان ياعيل",
			"بلفوريا",
			"بيت زايد",
			"بيت شعاريم",
			"بيت ليحم هجليليت",
			"تسيبوري",
			"تل عداشيم",
			"تل يوسف",
			"تمرات",
			"جان نير",
			"جدعونه",
			"جزيت",
			"جفت",
			"جفعات إيلا",
			"جيباع",
			"جينجار",
			"حانتون",
			"حجاجرة",
			"دبوريه",
			"دوبرات",
			"رام أون",
			"رمات تسفي",
			"رمات دافيد",
			"رمات يشاي",
			"رمانه",
			"رومات الهيب",
			"زرازير",
			"سجن شطا هجلبوع",
			"سديه يعقوب",
			"سريد",
			"سواعد حميرة",
			"سولم",
			"شبلي",
			"شمشيت",
			"صندله",
			"طرعان",
			"طمره (الجلبوع)",
			"عدي",
			"عيلوط",
			"عين حيروت",
			"عين دور",
			"عين ماهل",
			"قرية طباش",
			"كعبية",
			"كعبية طباش",
			"كفار باروخ",
			"كفار تابور",
			"كفار جدعون",
			"كفار نهر الأردن",
			"كفار هحورش",
			"كفر كنا",
			"كفر ميسر",
			"كفر يحزكيل",
			"كفر يهوشع",
			"ماجن شاؤول",
			"مجدال هعيمق",
			"مرحافيا كيبوتس",
			"مرحافيا موشاف",
			"مزراع",
			"مقيبلة",
			"منشية زبدة",
			"موقع تذكاري في غولاني",
			"نهلال",
			"نوريت",
			"نين",
			"هاردوف",
			"هسوليليم",
			"هوشيعا",
			"هيوجف",
			"وادي الحمام",
			"يافة الناصرة",
			"يزرعئيل",
			"يشوفي أمان",
			"يشوفي حيفر",
			"يفعات",
			"بن زكاي",
			"بني دروم",
			"بني رام",
			"بنيه",
			"بيت اليعزري",
			"بيت جمليئل",
			"بيت حلقية",
			"جان شلومو",
			"جان هدروم",
			"جاني طال",
			"جديره",
			"جفعات برنر",
			"جفعات واشنطون",
			"جيفتون",
			"حفيتس حاييم",
			"شدماه",
			"عشرت",
			"كدرون",
			"كرم بيبنة",
			"كريات عكرون",
			"كفار أفيف",
			"كفار مردخاي",
			"مجمع بني دروم",
			"مجموعة يافنيه",
			"مزكيرت باتيا",
			"مسجاف دوف",
			"مكان اقامة تستوفيا",
			"ميشر",
			"نيتسر حزاني",
			"نير جليم",
			"يافنيه",
			"يد بنيامين",
			"يسودوت",
			"",
			"",
			"أبو تلول وضواحيها",
			"أبو كرينات وضواحيها",
			"أم بطين وضواحيها",
			"اشليم",
			"المنطقة الصناعية ديمونا",
			"المنطقة الصناعية روتم",
			"بئر هداج وضواحيها",
			"بئير ميلخا",
			"تل السبع",
			"تلاليم",
			"حوره",
			"ديمونا",
			"رتميم",
			"رفيفيم",
			"سجن نفحة",
			"سديه بوكر",
			"سيجف شالوم وضواحيها",
			"شانطي في الصحراء",
			"عبدات",
			"عراد",
			"عروعر (عرعرة النقب)",
			"عزوز",
			"قصر السير وضواحيها",
			"كحوله ومكحول",
			"كديش برنيع",
			"كسيفة وضواحيها",
			"كمهين",
			"متسفي رمون",
			"مدرشت بن غوريون",
			"مرحاف عام",
			"مشأفي ساديه",
			"منطقة مفرق شوكات",
			"مولدا, السيد وضواحيها",
			"نيتسانه",
			"وادي النعم",
			"وتل عراد والافرهديج",
			"يروحام",
			"حيفا غرب",
			"حيفا الكرمل والبلاد التحت",
			"حيفا- كرايوت",
			"حيفا نيفيه شعنان",
			"طيرات كرمل",
			"كفار جاليم",
			"نيشر",
			"هحوتريم",
			"",
			"أحيطوف",
			"أليشيف",
			"أومتس",
			"أيال",
			"افيحايل",
			"الطيبه",
			"الطيرة",
			"المركز الأكاديمي روبين",
			"المنطقة الصناعية طيره.",
			"المنطقة الصناعية عيمك حيفر",
			"اليخين",
			"بئروتايم",
			"بات حيفر",
			"بات حين",
			"بلدة بوحن",
			"بني درور",
			"بورجاتا",
			"بيت أهرون",
			"بيت حزون",
			"بيت حيروت",
			"بيت هليفي",
			"بيت يتسحاق- شاعار حيفر",
			"بيت يناي",
			"تسور ناتان",
			"تسور يتسحاق",
			"تسورن",
			"تل موند",
			"تنوفوت",
			"ثسور موشيه",
			"جئولي تيمان",
			"جئوليم",
			"جان ياشيه",
			"جانوت هدر",
			"جفعات حاييم مؤوحاد",
			"جفعات شفيرا",
			"جيفعات حاييم إيحود",
			"حاجالاه",
			"حروت",
			"حنيئل",
			"حوفيت",
			"حيرف لأت",
			"حيفات تسيون",
			"رمات هخوبش",
			"زيمر",
			"شاعر إفرايم",
			"شوشنة هعمكيم",
			"عزريئيل",
			"عولش",
			"عين سريد",
			"عين هحورش",
			"عين ورد",
			"فردسيا",
			"فورات",
			"قلنسوة",
			"كفار عفوداه",
			"كفار فيتكين",
			"كفار موناش",
			"كفار هروئي",
			"كفار هس",
			"كفر حاييم",
			"كفر ياعبيس",
			"كفر يديدياه",
			"كفر يونه",
			"كيدماه",
			"مخمورت",
			"مشمار هشرون",
			"مشمورت",
			"معفروت",
			"نعوريم",
			"نورديه",
			"نيتسني عوز",
			"هدار عام",
			"هعوغن",
			"هفاتسيليت هشارون",
			"همفعيل",
			"ياعف",
			"يد حنا",
			"ينوف",
			"",
			"أدميت",
			"أفيريم",
			"أفيفيم",
			"إيفين مناحيم",
			"البقيعة",
			"الجش",
			"الغجر",
			"الكوش",
			"المطلة",
			"المنطقة الصناعية أخزيف ميل",
			"المنطقة الصناعية رمات دلتو",
			"ايلون",
			"بتست",
			"برعام",
			"بن عامي",
			"بيت هيلل",
			"تسفعون",
			"تسوريئل",
			"تل حاي",
			"جعتون",
			"جورن",
			"جورنوت هجاليل",
			"جونن",
			"جيشير هزيف",
			"حرفيش",
			"حنيتا",
			"حوسن",
			"دان",
			"دفنا",
			"دلتون",
			"دوفيف",
			"ديشون",
			"راس الناقورة",
			"راموت نافتالي",
			"ريحانيه",
			"زرعيت",
			"ساعر",
			"سديه ناحميه",
			"سعسع",
			"سنير",
			"شآر يشوف",
			"شتولا",
			"شفي تسيون",
			"شلومي",
			"شمير",
			"شومره",
			"عبدون",
			"عبرون",
			"عرب العرامشة",
			"علماه",
			"عمير",
			"عين يعقوب",
			"فسوطة",
			"كابري",
			"كرم بن زمره",
			"كريات شمونه",
			"كفار بلوم",
			"كفار جلعادي",
			"كفار سالد",
			"كفار فراديم",
			"لهفوت هباشان",
			"ليمن",
			"مانوت",
			"متات",
			"متسوفا",
			"مدرسة سده ميرون",
			"مرجليوت",
			"مسجاف عام",
			"معلوت ترشيحا",
			"معليا",
			"معوناه",
			"معيان باروخ",
			"ملاخيا",
			"مناره",
			"نؤوت مردخاي",
			"نافيه زيف",
			"نتوعاه",
			"نهاريا",
			"هجوشريم",
			"هيلا",
			"ياعره",
			"يحيعام",
			"يرئون",
			"يفتاح",
			"يوفل",
			"آزور",
			"أور يهودا",
			"بات يام",
			"بني براك",
			"تل أبيب جنوب ويافا",
			"تل- أبيب- شرق",
			"تل أبيب مركز المدينة",
			"تل أبيب هيركون",
			"جاني تكفا",
			"جفعات شموئيل",
			"جفعتايم",
			"حولون",
			"رمات غان- شرق",
			"رمات غان غرب",
			"سفيون",
			"كريات أونو",
			"مكفيه اسرائيل",
			"يهود- مونوسون",
			"الفريديس",
			"بات شلومو",
			"بيت تسفي",
			"تسروفا",
			"جيبع كرميل",
			"دور",
			"عتليت",
			"عوفر",
			"عين أييلا",
			"عين حود",
			"عين كرمل",
			"عين هود",
			"كرم مهرال",
			"كفار هنوعر يمين أورد",
			"مئير شفيه",
			"مجاديم",
			"مجلس اقلمي نير عتسيون",
			"مركز ميراب",
			"نافيه يام",
			"نحشوليم",
			"نير عتسيون",
			"هبونيم",
			"",
			"أحيه",
			"أفني حيفتس",
			"ألفي مناشيه",
			"ألون موريه",
			"أورنيت",
			"إيتمار",
			"ارئييل",
			"الكنا",
			"المنطقة الصناعية برأون",
			"المنطقة الصناعية شاعار بني",
			"بدوئيل",
			"بركان",
			"بروخين",
			"بساجوت",
			"بيت أريه",
			"بيت إيلا",
			"بيت حورون",
			"تسوفين",
			"تل تسيون",
			"تل مناشيه",
			"تلمون",
			"جاني موديعين",
			"جيفع بنيامين",
			"حرشا",
			"حرميش",
			"حشمونئيم",
			"حلميش",
			"حينانيت",
			"دوليف",
			"رحاليم",
			"ريحان",
			"ريففا",
			"ريمونيم",
			"سلعيت",
			"شاكيد",
			"شبوت رحل",
			"شعاري تكفاه",
			"شيفي شومرون",
			"شيلو",
			"عدي عد",
			"عطرت",
			"علي",
			"علي زاهاف",
			"عمنوئيل",
			"عميحاي",
			"عوفرا",
			"عوفريم",
			"عيتس افرايم",
			"عيناب",
			"كدوميم",
			"كرني شومرون",
			"كريات نتافيم",
			"كفار تبواح",
			"كفار هأورنيم",
			"كوخاف هشاحار",
			"كوخاف يئير",
			"كوخاف يعقوب",
			"كيده",
			"ماتحياهو",
			"مافو حورون",
			"مافو دوتان",
			"مجدليم",
			"مزرعت يائير",
			"معاليه شومرون",
			"معليه لبونا",
			"معليه مخمش",
			"موديعين عيليت",
			"ميجرون",
			"ناحليئل",
			"نريا",
			"نعلاه",
			"نفي سموئيل",
			"نوفيم",
			"نوفيه نحاميه",
			"نيلي",
			"هار براخا",
			"يتسهار",
			"يكير",
			"",
			"أرسوف",
			"أليشمع",
			"اوديم",
			"ايفين يهودا",
			"بصرة",
			"بني تسيون",
			"بيت بيرل",
			"بيت يهوشاع",
			"تسوفيت",
			"تل يتسحاق",
			"جاعاش",
			"جان حايم",
			"جاني عام",
			"جفعات حين",
			"جلجوليه",
			"حاجور",
			"حروتسيم",
			"حورشيم",
			"راموت هشفيم",
			"رشبون",
			"رعنانا",
			"رمات هشارون",
			"سجن هشرون",
			"سديه حيمد",
			"سديه وربورغ",
			"شفييم",
			"عدانيم",
			"كفار سابا",
			"كفار شمرياهو",
			"كفر برا",
			"كفر قاسم",
			"كفر ملول",
			"كفر نيطر",
			"متان",
			"معهد فينجيت",
			"نافيه يمين",
			"نافيه ييرك",
			"نتانيا - شرق",
			"نتانيا- غرب",
			"نير الياهو",
			"نيريت",
			"هرتسليا - المركز وجليل يام",
			"هرتسليا- بيتوح",
			"هود هشارون",
			"يرحيب",
			"يركونة",
			"يكوم",
			"إيليفازوتمنع",
			"بئير أوره",
			"تسوفر",
			"تسوكيم",
			"جروفيت",
			"حايي بار يوتفاتا",
			"حتسفه",
			"حضيرة عردال",
			"سفير",
			"سمر",
			"شحروت",
			"شيطيم",
			"عيدان",
			"عير أوفوت",
			"عين حتسفا",
			"عين ياهاف",
			"فارن",
			"كتوراه",
			"كوشي ريمون",
			"لوطن",
			"نؤوت سمدار",
			"نافيه حريف",
			"ياهل",
			"يوطفاتا",
			"",
			"",
			"أشبول",
			"أوريم",
			"أوفكيم",
			"إيشل هنسي",
			"باروش",
			"بدوئييم",
			"برور حيال",
			"بطحا",
			"بعامي تشاز",
			"تاشور",
			"تدهار",
			"تسئليم",
			"تفراح",
			"تلمي بيلو",
			"جفولوت",
			"جيلات",
			"دوروت",
			"روحماه",
			"رينن",
			"زروعه",
			"سديه تسفي",
			"شرشرت",
			"شيبوليم",
			"شيفي دروم",
			"فطيش",
			"كريات حينوخ مرحافيم",
			"كلحيم",
			"مزرعة شيكميم",
			"مسلول",
			"معجاليم، جفعوليم، مليلوت",
			"مفوعيم",
			"نتيفو",
			"نير عكيفا",
			"نير موشيه",
			"وبيت هجدي",
			"يوشيبياه",
			"أشكلون",
			"المنطقة الصناعية الجنوبية",
			"المنطقة الصناعية الشمالية",
			"بئير جانيم",
			"بات هدار",
			"براخيا",
			"بيت شيكما",
			"تلمي يافه",
			"جيئاه",
			"حيلتس",
			"كفر سيلفير",
			"كوخاف ميخائيل",
			"مشعان",
			"مفكيعيم",
			"نيتسان",
			"نيتسان",
			"نيتسانيم",
			"نير اسرائيل",
			"هوديا",
			"",
			"",
			"",
			"",
			"",
			"",
			"أور هنير",
			"إيرز",
			"افيشالوم",
			"بئيري",
			"بري جان",
			"بني نتسريم",
			"تسوحار واوهاد",
			"تكومه",
			"تكومه ومزرعة يزراعم",
			"تلمي إلياهو",
			"تلمي يوسف",
			"جفرعام",
			"حوليت",
			"ديكل",
			"رعيم",
			"زيكيم",
			"زيمرات وشوفا",
			"ساحة القواس نير عام",
			"سديه أبراهام",
			"سديه نيتسان",
			"سعد",
			"سوفه",
			"شدموت، إيفيم،",
			"شلوميت",
			"شوكداه",
			"علوميم",
			"عين هبسور",
			"عين هشلوشا",
			"غزه",
			"كرم شلوم",
			"كرميه",
			"كفار ميمون وتوشيا",
			"كلية سفير",
			"كيسوفيم",
			"ماجن",
			"مفتاحيم، عاميعوز، ييشع",
			"مفلسيم",
			"ناحل عوز",
			"نافيه",
			"نتيف هعسراه",
			"نير عام",
			"نير عوز",
			"نير يتسحاك",
			"نيريم",
			"ياتد",
			"ياخيني",
			"يبول",
			"يد موردخاي",
			"",
			"المنطقة الصناعية تسفئيم",
			"بيت ألفا وحفتسفا",
			"بيت هشيتا",
			"بيت يوسف",
			"بيسان",
			"تل تؤوميم",
			"جيشير",
			"حمدية",
			"رحوف",
			"رشافيم",
			"روية",
			"سديه إلياهو",
			"سديه تروموت",
			"سديه ناحوم",
			"شلفيم",
			"شلوحوت",
			"طيرات تسفي",
			"عين هنتسيف",
			"كفار روبين",
			"كفر جميلة ملخيشوع",
			"مزرعة عيدن",
			"مسيلوت",
			"معليه جلبوع",
			"معوز حييم",
			"منحميه",
			"مولدت",
			"ميراف",
			"نافيه أور",
			"نافيه إيتان",
			"نير دافيد",
			"ياردينا",
			"أنيعام",
			"الماغور",
			"تل كتسير",
			"جفعات أفني",
			"حاد نيس",
			"راموت",
			"شاعال",
			"شاعر هجولان",
			"عين جيف",
			"كاتسرين المنطقة الصناعية",
			"كتسرين",
			"كفار كيش",
			"كناف",
			"كيدمات تسفي",
			"كيلع",
			"مساده",
			"معجان",
			"معليه جملا",
			"هاون",
			"أورنيم",
			"أوشة",
			"ابطن",
			"الخوالد غرب",
			"المنطقة الصناعية شاعر نعما",
			"بسمة طبعون",
			"خوالد",
			"راس علي",
			"رخاسيم",
			"رمات يوحانان",
			"شاعر هعامكيم",
			"كريات اتا",
			"كريات بياليك",
			"كريات تبعون",
			"كريات موتسكين",
			"كريات يام",
			"كفار بياليك",
			"كفار تكفا",
			"كفار حسيديم",
			"كفار حسيديم",
			"كفار همكابي",
			"مقبرة تل ريجيف",
			"نوفيت",
			"ياجور",
			"أحفا",
			"أحوزام",
			"أشدود- أ،ب،د، هـ",
			"أشدود- ج، و، ز",
			"أشدود- ح، ط، ي، ي ج،ي د، ط ز",
			"أشدود- ي أ، ي ب، ط و، ي ز، مري",
			"ألوما",
			"أمونيم",
			"أوروت",
			"افيغدور",
			"ال عازي",
			"الروحة",
			"المنطقة الصناعية الشمالية,",
			"المنطقة الصناعية تيموريم",
			"المنطقة الصناعية عاد هلوم",
			"المنطقة الصناعية كنوت",
			"ايتان",
			"ايفين شموئيل",
			"بئير طوبيا",
			"بارك صناعة رام",
			"بني عايش",
			"بيت جوبرين",
			"بيت عزرا",
			"بيت نير",
			"بيتسرون",
			"تلمي يحيئل",
			"تلميم",
			"تيموريم",
			"جان يفنه",
			"جت",
			"جفعاتي",
			"جيلون",
			"حتسور",
			"حيتسف",
			"رفاديم",
			"زبدئيل",
			"زرحيه",
			"زوهر",
			"سجولا",
			"سديه دافيد",
			"سديه عوزياهو",
			"سديه موشيه",
			"سديه يواف",
			"شاحار",
			"شتوليم",
			"شفير",
			"شلفاه",
			"عازر",
			"عروجوت",
			"عزريكم",
			"عوتسم",
			"عوزة",
			"عين تسوريم",
			"فردون",
			"قرية الريف ومفرق رأم",
			"كريات غات , كرمي جات",
			"كريات ملاخي",
			"كفار أحيم",
			"كفار مناحيم",
			"كفار وربورغ",
			"كنوت",
			"كومميوت",
			"كيدما",
			"لخيش",
			"مركز شفيرا",
			"مسوؤت يتسحاق",
			"منوحاه",
			"نافيه مبطاح",
			"نجبا",
			"نحالا",
			"نهورا",
			"نوجه",
			"نوعام",
			"نير بنيم",
			"نير حين",
			"يد نتان",
			"ينون",
			"اللقية وضواحيها",
			"المنطقة الصناعية عيدان الن",
			"بئر السبع -  شرق",
			"بئر السبع - شمال",
			"بئر السبع - غرب",
			"بئر السبع -جنوب",
			"بيت كاما",
			"ترابين الصانع وضواحيها",
			"جفاعوت بار",
			"حتسريم",
			"دبير",
			"رهط وضواحيها",
			"شوبل",
			"شومرياه",
			"عومر",
			"كرميت",
			"كرميم",
			"لاهف",
			"لهافيم",
			"مشمار هنيجف",
			"ميتار",
			"نفاتيم",
			"نيئوت حوفاف",
			"",
			"أفيئيل",
			"ألوني يتسحاق",
			"أور عكيفا",
			"الخضيرة - نافيه يام",
			"الخضيرة- شرق",
			"الخضيرة- غرب",
			"المنطقة الصناعية رجافيم",
			"المنطقة الصناعية قيساريا",
			"المنطقة الصناعية مافو الكر",
			"المنطقة الصناعية يوكنعام ع",
			"الياكيم",
			"بارديس حانه",
			"بنيامينا",
			"بيت حنانيه",
			"تلمي إليعيزر",
			"جان شموئيل",
			"جان هشومرون",
			"جسر الزرقاء",
			"جفعات حبيياه",
			"جفعات عوز",
			"جفعات عيدا",
			"جفعات نيلي",
			"جلعاد (ايفين يتسحاق)",
			"خضيرة- مركز",
			"داليه",
			"راموت منشيه",
			"رجافيم",
			"رمات هشوفط",
			"رمات هنديف",
			"زخرون يعقوب",
			"سجن مجدو",
			"سدوت يام",
			"سديه يتسحاق",
			"شاعر منشيه",
			"عميكام",
			"عين شيمر",
			"عين عيرون",
			"عين هشوفط",
			"عين هعيمك",
			"قيساريا",
			"كركور",
			"كفار بينس",
			"كفار جليكسون",
			"مئور",
			"مجيدو",
			"مدراخ عوز",
			"مدرسة أورط بنيامينا",
			"مركز بحري قيساريا",
			"مشمار هعيمك",
			"مشمورت",
			"معجان ميخائيل",
			"معنيت",
			"معيان تسفي",
			"يوكنعام عيليت",
			"يوكنعام هموشافه وهزورع",
			"",
			"العريان",
			"ام الفحم",
			"ام القطف",
			"باقة الغربية",
			"برطعه",
			"بركاي",
			"جت",
			"حريش",
			"عرعرة",
			"عين السهلة",
			"كتسير",
			"كفر قرع",
			"لهافوت حبيية",
			"متسبيه إيلان",
			"مجال",
			"معاوية",
			"معليه عيرون",
			"مي عامي",
			"ميتسر",
			"ميسر",
			"المنطقة الصناعية أفيك وليف",
			"ايلعاد",
			"بئروت يتسحاق",
			"بركات",
			"بني عطاروت",
			"بيت عريف",
			"بيت نحميا",
			"بيتح تيكفا",
			"تعسيون حاتساف",
			"جت ريمون",
			"جفعات كواح",
			"جفعات هشلوشا",
			"حديد",
			"راس العين",
			"رينتيه",
			"شوهام",
			"طيرات يهودا",
			"عينات",
			"كفار سيركين",
			"كفر ترومن",
			"مازور",
			"مجشيميم",
			"معش",
			"نحشونيم",
			"نحليم",
			"نوفخ",
			"أشكولوت",
			"إفرات",
			"ألون",
			"ألون شابوت",
			"أليآف",
			"أمتسيا",
			"ادورا",
			"الخليل",
			"العيزر",
			"المنطقة الصناعية ميتاريم",
			"بات عاين",
			"بني دكاليم",
			"بني كيدم",
			"بيت حاجاي",
			"بيت يتير",
			"بيتار عيليت",
			"تاني عومريم",
			"تكوع",
			"تيلم",
			"جفاعوت",
			"راس تسوريم",
			"سنسنه",
			"سوسيا",
			"شاني ليفنه",
			"شمعا",
			"شيكف",
			"عتنيئل",
			"علمون",
			"كدار",
			"كرمل",
			"كرمي تسور",
			"كرمي كطيف",
			"كريات أربع",
			"كفار أدوميم",
			"كفار الداد",
			"كفار عتسيون",
			"متسبي يريحو",
			"مجدل عوز",
			"مزرعة حقل بار",
			"معاليه حيفر",
			"معليه أدوميم",
			"معليه عاموس",
			"معون",
			"ميتساد",
			"نافيه دانيئيل",
			"نجوهوت",
			"نوفي فرت",
			"نوكديم",
			"نيطع",
			"هار جيلو",
			"هار عمشا"
	)));

	private final Set<String> districts;

	LanguageUtil(Set<String> districts)
	{
		this.districts = districts;
	}

	public Set<String> getDistricts()
	{
		return districts;
	}
}